Installer:
- InstallerUrl: https://github.com/SchildiChat/schildichat-desktop/releases/download/v1.11.36-sc.3/SchildiChat_Setup_v1.11.36-sc.3.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    - Fix compact room list avatars
    - Fix crash with collapsed buttons
- Key: ReleaseNotesUrl
  Value: https://github.com/SchildiChat/schildichat-desktop/releases/tag/v1.11.36-sc.3
Version: 1.11.36-sc.3
ReleaseTime: 2024-02-26T18:57:40.0000000Z
