Installer:
- Architecture: x86
  InstallerUrl: https://github.com/jesseduffield/lazygit/releases/download/v0.45.0/lazygit_0.45.0_Windows_32-bit.zip
- Architecture: x64
  InstallerUrl: https://github.com/jesseduffield/lazygit/releases/download/v0.45.0/lazygit_0.45.0_Windows_x86_64.zip
- Architecture: arm64
  InstallerUrl: https://github.com/jesseduffield/lazygit/releases/download/v0.45.0/lazygit_0.45.0_Windows_arm64.zip
- Architecture: neutral
  InstallerUrl: https://github.com/jesseduffield/lazygit/releases/download/v0.45.0/lazygit_0.45.0_Windows_armv6.zip
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Lots of great improvements in this one! Thanks to all the contributors who helped make this release happen.
    Apologies for the long waits between releases. As of https://github.com/jesseduffield/lazygit/pull/4146 we're now (almost) guaranteed to do monthly releases.
    What's Changed
    Enhancements 🔥
    - Better branch delete confirmation by @stefanhaller in https://github.com/jesseduffield/lazygit/pull/3915
    - Add a menu item to delete both local and remote branch at once by @stefanhaller in https://github.com/jesseduffield/lazygit/pull/3916
    - Auto-render hyperlinks by @stefanhaller in https://github.com/jesseduffield/lazygit/pull/3914
    - Allow pasting commits multiple times by @stefanhaller in https://github.com/jesseduffield/lazygit/pull/3983
    - Add config option to disable switching tabs with panel jump keys (and disable by default) by @hgreenstein in https://github.com/jesseduffield/lazygit/pull/3927
      - We jumped the gun on this change in the last release: having the number key both select a panel and switch tabs was bad for muscle memory so it's that behaviour is now disabled by default.
    - Add new filter to only show tracked files in Files panel by @veremenko-y in https://github.com/jesseduffield/lazygit/pull/4024
    - Allow DiffContextSize to be decreased to zero by @LuxxxLucy in https://github.com/jesseduffield/lazygit/pull/4050
    - Allow user to select remote and branch when creating a PR by @moha-gh in https://github.com/jesseduffield/lazygit/pull/1889
    - Delete range selection of branches by @stefanhaller in https://github.com/jesseduffield/lazygit/pull/4073
    - Show the number of lines changed per file in working file tree view by @johannaschwarz in https://github.com/jesseduffield/lazygit/pull/4015
    - Drop merge commits by @stefanhaller in https://github.com/jesseduffield/lazygit/pull/4094
    - Wrap lines in staging view by @stefanhaller in https://github.com/jesseduffield/lazygit/pull/4098
    - Allow to switch branches in Commit View (#4115) by @seflue in https://github.com/jesseduffield/lazygit/pull/4117
    - Allow on prem Azure DevOps Server pull request by @waynebowie99 in https://github.com/jesseduffield/lazygit/pull/3954
    - Add screen-mode command line argument by @alewis001 in https://github.com/jesseduffield/lazygit/pull/4103
    - Default to half-screen mode when opening with certain CLI args by @jesseduffield in https://github.com/jesseduffield/lazygit/pull/4141
    - Show the alt-enter keybinding at bottom of commit description view by @stefanhaller in https://github.com/jesseduffield/lazygit/pull/4136
    - Add number of commits to cherry-pick confirmation prompt by @brandondong in https://github.com/jesseduffield/lazygit/pull/4158
    Fixes 🔧
    - Fix copying commit author to clipboard by @stefanhaller in https://github.com/jesseduffield/lazygit/pull/3936
    - Fix merge conflict resolution when file doesn't end with a LF by @stefanhaller in https://github.com/jesseduffield/lazygit/pull/3976
    - Fix file icons by @stefanhaller in https://github.com/jesseduffield/lazygit/pull/3975
    - Fix non-sticky range select after clicking in staging view by @stefanhaller in https://github.com/jesseduffield/lazygit/pull/3998
    - Fix scroll position when entering staging view by clicking in the main view by @stefanhaller in https://github.com/jesseduffield/lazygit/pull/3992
    - Fix mouse wheel scrolling of custom patch view by @stefanhaller in https://github.com/jesseduffield/lazygit/pull/4089
    - Improve editing a commit by @stefanhaller in https://github.com/jesseduffield/lazygit/pull/4090
    - Use custom context size in range diff by @stefanhaller in https://github.com/jesseduffield/lazygit/pull/4082
    - commits panel: add missing default sort order by @phanirithvij in https://github.com/jesseduffield/lazygit/pull/4097
    - Fix issues with opening links and files using WSL by @bottino in https://github.com/jesseduffield/lazygit/pull/3850
    - Fix moving a commit across a branch boundary in a stack of branches by @stefanhaller in https://github.com/jesseduffield/lazygit/pull/4096
    - Don't preserve commit message when it's unchanged from initial message by @stefanhaller in https://github.com/jesseduffield/lazygit/pull/4110
    - Fix hang when returning from shell command by @stefanhaller in https://github.com/jesseduffield/lazygit/pull/4126
    - Prevent killing of unrelated processes on windows by @jesseduffield in https://github.com/jesseduffield/lazygit/pull/4137
    - Add worktree option to fast forwarding operation by @john-mutuma in https://github.com/jesseduffield/lazygit/pull/4051
    - Don't show keybindings option in bottom line when panel is open by @stefanhaller in https://github.com/jesseduffield/lazygit/pull/4143
    - Fix reset/rebase to upstream by @stefanhaller in https://github.com/jesseduffield/lazygit/pull/4151
    - Avoid blank line at end of view by @stefanhaller in https://github.com/jesseduffield/lazygit/pull/4152
    - Adjust line number for working copy when editing a line by @stefanhaller in https://github.com/jesseduffield/lazygit/pull/4119
    - Fix micro editor preset by @kytta in https://github.com/jesseduffield/lazygit/pull/4156
    - Use interactive shell for running shell commands only if shell is bash or zsh by @stefanhaller in https://github.com/jesseduffield/lazygit/pull/4159
    Maintenance ⚙️
    - Add performance improvements section to release notes by @jesseduffield in https://github.com/jesseduffield/lazygit/pull/3922
    - ci: update upload-artifact and download-artifact actions to v4 by @Juneezee in https://github.com/jesseduffield/lazygit/pull/4063
    - Let schema/config.json end with a line feed by @stefanhaller in https://github.com/jesseduffield/lazygit/pull/4092
    - Saner view geometry by @stefanhaller in https://github.com/jesseduffield/lazygit/pull/4085
    - Cleanup background fetch by @stefanhaller in https://github.com/jesseduffield/lazygit/pull/4084
    - remove duplicate secondary MouseWheelUp keybind by @samueldominguez in https://github.com/jesseduffield/lazygit/pull/4120
    - enhancement: Use HEX colors on file icons instead of C256 colors by @hasecilu in https://github.com/jesseduffield/lazygit/pull/4029
    - chore: use errors.New to replace fmt.Errorf with no parameters by @RiceChuan in https://github.com/jesseduffield/lazygit/pull/4107
    - Fix typos by @NathanBaulch in https://github.com/jesseduffield/lazygit/pull/3920
    - Bump crypto and net packages by @jesseduffield in https://github.com/jesseduffield/lazygit/pull/4144
    - Tweak file icons by @jesseduffield in https://github.com/jesseduffield/lazygit/pull/4145
    - Standardise on 'screen mode' naming convention by @jesseduffield in https://github.com/jesseduffield/lazygit/pull/4142
    Docs 📖
    - Fix installation for Ubuntu in README.md by @shaobosong in https://github.com/jesseduffield/lazygit/pull/4031
    - Fixes to lazygit Ubuntu install instructions in README.md by @wrecklass in https://github.com/jesseduffield/lazygit/pull/3970
    - Fix typos by @skoch13 in https://github.com/jesseduffield/lazygit/pull/4121
    - Add vision and design principles doc by @jesseduffield in https://github.com/jesseduffield/lazygit/pull/4053
    - docs: Stylize and correct the NixOS section in README.md by @wadsaek in https://github.com/jesseduffield/lazygit/pull/4135
    - Update chinese translation for pull requests by @jesseduffield in https://github.com/jesseduffield/lazygit/pull/4140
    - Set repology table to 3 columns by @hasecilu in https://github.com/jesseduffield/lazygit/pull/4138
    - Update instructions for using OSC52 with tmux by @EliasA5 in https://github.com/jesseduffield/lazygit/pull/3597
    - Update docs to describe use of custom commands without keybindings by @a-jentleman in https://github.com/jesseduffield/lazygit/pull/3846
    - documentation - describe os.openLink by @smangels in https://github.com/jesseduffield/lazygit/pull/3094
    - Clarify commit message prefix mechanics by @zeromask1337 in https://github.com/jesseduffield/lazygit/pull/4114
    New Contributors
    - @shaobosong made their first contribution in https://github.com/jesseduffield/lazygit/pull/4031
    - @hgreenstein made their first contribution in https://github.com/jesseduffield/lazygit/pull/3927
    - @wrecklass made their first contribution in https://github.com/jesseduffield/lazygit/pull/3970
    - @veremenko-y made their first contribution in https://github.com/jesseduffield/lazygit/pull/4024
    - @LuxxxLucy made their first contribution in https://github.com/jesseduffield/lazygit/pull/4050
    - @phanirithvij made their first contribution in https://github.com/jesseduffield/lazygit/pull/4097
    - @bottino made their first contribution in https://github.com/jesseduffield/lazygit/pull/3850
    - @johannaschwarz made their first contribution in https://github.com/jesseduffield/lazygit/pull/4015
    - @samueldominguez made their first contribution in https://github.com/jesseduffield/lazygit/pull/4120
    - @skoch13 made their first contribution in https://github.com/jesseduffield/lazygit/pull/4121
    - @wadsaek made their first contribution in https://github.com/jesseduffield/lazygit/pull/4135
    - @seflue made their first contribution in https://github.com/jesseduffield/lazygit/pull/4117
    - @waynebowie99 made their first contribution in https://github.com/jesseduffield/lazygit/pull/3954
    - @EliasA5 made their first contribution in https://github.com/jesseduffield/lazygit/pull/3597
    - @alewis001 made their first contribution in https://github.com/jesseduffield/lazygit/pull/4103
    - @a-jentleman made their first contribution in https://github.com/jesseduffield/lazygit/pull/3846
    - @john-mutuma made their first contribution in https://github.com/jesseduffield/lazygit/pull/4051
    - @RiceChuan made their first contribution in https://github.com/jesseduffield/lazygit/pull/4107
    - @NathanBaulch made their first contribution in https://github.com/jesseduffield/lazygit/pull/3920
    Full Changelog: https://github.com/jesseduffield/lazygit/compare/v0.44.1...v0.45.0
- Key: ReleaseNotesUrl
  Value: https://github.com/jesseduffield/lazygit/releases/tag/v0.45.0
Version: 0.45.0
ReleaseTime: 2025-01-11T04:10:48.0000000Z
