Installer:
- Architecture: x64
  InstallerUrl: https://github.com/uazo/cromite/releases/download/v125.0.6422.113-b965da17241bca9fbb27b3137d44a28629f45eeb/chrome-win.zip
  NestedInstallerFiles:
  - RelativeFilePath: chrome-win\chrome.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: see https://github.com/uazo/cromite/issues/1142#issuecomment-2131225045
- Key: ReleaseNotesUrl
  Value: https://github.com/uazo/cromite/releases/tag/v125.0.6422.113-b965da17241bca9fbb27b3137d44a28629f45eeb
Version: 125.0.6422.113
ReleaseTime: 2024-05-26T13:01:33.0000000Z
