Installer:
- Architecture: x64
  InstallerUrl: https://github.com/uazo/cromite/releases/download/v130.0.6723.59-00f5239a3c15b6c898b246664f654c19f25b9122/chrome-win.zip
  NestedInstallerFiles:
  - RelativeFilePath: chrome-win\chrome.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: see https://github.com/uazo/cromite/issues/1559#issuecomment-2419259878
- Key: ReleaseNotesUrl
  Value: https://github.com/uazo/cromite/releases/tag/v130.0.6723.59-00f5239a3c15b6c898b246664f654c19f25b9122
Version: 130.0.6723.59
ReleaseTime: 2024-10-17T11:26:17.0000000Z
