Installer:
- Architecture: x64
  InstallerUrl: https://github.com/uazo/cromite/releases/download/v123.0.6312.105-0068783e64f8db299bce32bb8016de2accc43d05/chrome-win.zip
  NestedInstallerFiles:
  - RelativeFilePath: chrome-win\chrome.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: see https://github.com/uazo/cromite/issues/949
- Key: ReleaseNotesUrl
  Value: https://github.com/uazo/cromite/releases/tag/v123.0.6312.105-0068783e64f8db299bce32bb8016de2accc43d05
Version: 123.0.6312.105
ReleaseTime: 2024-04-04T14:16:42.0000000Z
