Installer:
- Architecture: x64
  InstallerUrl: https://github.com/uazo/cromite/releases/download/v123.0.6312.58-f5d7de125b76b46401894105d589377b2d402249/chrome-win.zip
  NestedInstallerFiles:
  - RelativeFilePath: chrome-win\chrome.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: see https://github.com/uazo/cromite/issues/908
- Key: ReleaseNotesUrl
  Value: https://github.com/uazo/cromite/releases/tag/v123.0.6312.58-f5d7de125b76b46401894105d589377b2d402249
Version: 123.0.6312.58
ReleaseTime: 2024-03-21T13:31:52.0000000Z
