Installer:
- Architecture: x64
  InstallerUrl: https://github.com/uazo/cromite/releases/download/v123.0.6312.86-ffc5de1ec79365f621a8624543b364bf8664ac77/chrome-win.zip
  NestedInstallerFiles:
  - RelativeFilePath: chrome-win\chrome.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: ""
- Key: ReleaseNotesUrl
  Value: https://github.com/uazo/cromite/releases/tag/v123.0.6312.86-ffc5de1ec79365f621a8624543b364bf8664ac77
Version: 123.0.6312.86
ReleaseTime: 2024-03-28T13:08:12.0000000Z
