Installer:
- Architecture: x64
  InstallerUrl: https://github.com/dbeaver/dbeaver/releases/download/24.0.5/dbeaver-ce-24.0.5-x86_64-setup.exe
- Architecture: x64
  InstallerUrl: https://github.com/dbeaver/dbeaver/releases/download/24.0.5/dbeaver-ce-24.0.5-x86_64-setup.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    - SQL Editor:
                    - Smart mode for statement delimiter was improved
                    - Default option for the setting 'Blank line is statement delimiter' was changed to 'Always'
                    - Cursor behavior during autocompletion was improved
                    - Code highlighting issue with a quoted identifier in case of no connection was fixed
                    - High CPU usage for large script was fixed
                - Metadata Editor:
                    - Highlighting for created entities was changed to green
                    - Virtual foreign keys: reference table container selector was fixed
                - Database Navigator: CTRL+C and other shortcuts behavior after the application startup were fixed
                - AI (extension): custom scope performance was improved
                - General:
                    - Opening editors for files with special symbols in names was fixed
                    - Portable distribution of the application was fixed (config files location)
                    - Licensing for some source files was fixed
                - Eclipse plugin: new database objects create was fix
                - Databases
                    - DuckDB: Spatial data visualization support was added
                    - Oracle:
                        - Partition type display was added
                        - Materialized view refresh was fixed
                    - SQL Server: Default IDENTITY was changed to (1,1) (thanks to @Sgierek106)
                    - Vertica: LOOP - END LOOP as a block and DECLARE were added to the syntax analyser
- Key: ReleaseNotesUrl
  Value: https://github.com/dbeaver/dbeaver/releases/tag/24.0.5
Version: 24.0.5
ReleaseTime: 2024-05-19T15:22:19.0000000Z
