Installer:
- Architecture: x64
  InstallerUrl: https://github.com/dbeaver/dbeaver/releases/download/24.0.0/dbeaver-ce-24.0.0-x86_64-setup.exe
- Architecture: x64
  InstallerUrl: https://github.com/dbeaver/dbeaver/releases/download/24.0.0/dbeaver-ce-24.0.0-x86_64-setup.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Changes since 23.3.5:
                - SQL Editor:
                    - Nested CASE statements were supported
                    - Deleting queries from Outline was fixed
                    - Type casts support was improved
                    - Handling of right-click on collapsed query was fixed
                    - Expanding collapsed group after the code execution was fixed
                - Metadata editor: changing the key name when a constraint is changed
                - Data Editor: SRID switching in the Spatial data viewer was fixed
                - ER Diagram:
                    - Missing connection lines were fixed
                    - Mikami-Tabuchi routing type was disabled
                - AI:
                    - Comment presentation was improved
                    - Sending unique keys and indexes was fixed
                - Data Transfer:
                    - Export statistic was fixed
                    - Import blocking in case of table creation restriction was fixed
                    - Stack overflow on Linux was fixed
                - Connectivity: closing timeout for an idle connection was increased and disabled for embedded drivers
                - Security:
                    - Vulnerabilities display in Elasticsearch was fixed
                    - PosgtreSQL driver was upgraded due to CVE-2024-1597
                - General:
                    - Smart commit mode was enhanced: if the manual commit mode was enabled and just after it the query failed, the smart commit mode is enabled again
                    - Links between preference pages were fixed
                    - Issue with not found tables was fixed
                    - Release note display was corrected
                    - Driver libraries download was fixed
                    - Previous workspace format was supported
                    - Usage statistics popup was redesigned
                - Databases:
                    - DuckDB: WSL paths handling was fixed
                    - Greenplum: STRICT keyword was added to function definition
                    - Hana: Switch to the Kerberos authentication in the Connection page was fixed
                    - MariaDB: The exported JSON format was fixed
                    - MySQL and MariaDB:
                        - "Disable Triggers" option was added to the Context menu
                        - "Case-sensitive" option was added to the metadata search
                        - Databases with the same name but different name case are considered as different databases
                    - Oracle:
                        - Generating DDL for triggers was fixed
                    - SQL Server: additional table properties were added for tables and views in the properties editor
                    - Yellowbricks icons and link to the website were changed
- Key: ReleaseNotesUrl
  Value: https://github.com/dbeaver/dbeaver/releases/tag/24.0.0
Version: 24.0.0
ReleaseTime: 2024-03-09T10:23:09.0000000Z
