Installer:
- Architecture: x64
  InstallerUrl: https://github.com/dbeaver/dbeaver/releases/download/24.0.2/dbeaver-ce-24.0.2-x86_64-setup.exe
- Architecture: x64
  InstallerUrl: https://github.com/dbeaver/dbeaver/releases/download/24.0.2/dbeaver-ce-24.0.2-x86_64-setup.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    - Connectivity:
                    - Using multiple jumps tunnels when connecting via SSH was supported
                    - Enable tunnel sharing option was added
                    - Test connection was fixed
                - SQL Editor:
                    - WHERE TRUE and SELECT UNIQUE support was added
                    - Error with single quoted string was fixed
                    - Syntax highlighting after active schema change was fixed
                - Data Editor:
                    - Automatic row count option was added (thanks to @utsav1704)
                - Metadata editor:
                    - Deleting table comments was fixed
                    - Linking with the editor was fixed
                - General:
                    - Ability to collect log files from the interface was added
                    - Transaction rollback behavior was fixed
                    - Metadata changes were removed from the commit counter
                    - Autocommit in production databases was fixed
                - Data transfer:
                    - Ability to specify header case in the target file was added
                    - Typo in the confirmation dialog was fixed
                - Databases:
                    - Cubrid: Query plan feature was added (thanks to @rathana-pvs)
                    - Old MySQL drivers were repacked
                    - PostgreSQL: Jobs, roles, and system information were hidden in the Hide Folders mode
                    - SQLite: Deleting columns was fixed
- Key: ReleaseNotesUrl
  Value: https://github.com/dbeaver/dbeaver/releases/tag/24.0.2
Version: 24.0.2
ReleaseTime: 2024-04-07T17:14:46.0000000Z
