Installer:
- Architecture: x64
  InstallerUrl: https://github.com/dbeaver/dbeaver/releases/download/24.2.3/dbeaver-ce-24.2.3-x86_64-setup.exe
- Architecture: x64
  InstallerUrl: https://github.com/dbeaver/dbeaver/releases/download/24.2.3/dbeaver-ce-24.2.3-x86_64-setup.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    - SQL Editor:
                    - "Show values setting" in the autocompletion section is disabled by default due to performance issues
                    - Added highlighting and validation of synonyms
                    - Semantic error style was changed
                    - Fixed issues with highlighting that occurred when saving the script
                - Metadata: Fixed and exception that appeared on right click on table properties
                - Connectivity:
                    - Fixed an issue where script execution would not stop when disconnected
                    - Added an ability to export driver files from the "Edit driver" dialog
                    - Fixed user name display in SSH profile
                - Miscellaneous:
                    - Added additional Java configuration file independent of the product version update
                    - Added the ability to disable Windows Defender at startup, which speeds up application loading
                    - Some SWT errors were fixed
                    - Darkest Dark theme installation was fixed
                    - Added the ability to work with OS usernames containing special characters
                    - Git extension installation was fixed
                    - Eclipse license text was updated
                    - Fixed exception that appeared when loading procedure
                - Databases:
                    - BigQuery: Array and JSON display was improved
                    - Db2 z/OS: Fixed broken configuration for generic drivers
                    - DuckDB: BLOB display was fixed
                    - MySQL: Added support for table name in backticks for SQL Editor
                    - PostgreSQL: Permission editor was fixed
- Key: ReleaseNotesUrl
  Value: https://github.com/dbeaver/dbeaver/releases/tag/24.2.3
Version: 24.2.3
ReleaseTime: 2024-10-20T17:44:57.0000000Z
