Installer:
- Architecture: x64
  InstallerUrl: https://github.com/dbeaver/dbeaver/releases/download/24.3.3/dbeaver-ce-24.3.3-x86_64-setup.exe
- Architecture: x64
  InstallerUrl: https://github.com/dbeaver/dbeaver/releases/download/24.3.3/dbeaver-ce-24.3.3-x86_64-setup.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    - SQL Editor:
                    - Added support for SELECT INTO query smart completion
                    - Changed shortcuts for result set zoom: Ctrl+Aalt+0 and Ctrl+Alt+9
                    - Fixed the order of completion suggestions in the proposals list
                    - New completion engine:
                        - Fixed a bug with duplicating alias part during column completion
                        - Fixed autocomplete for join conditions when multiple joins are present
                        - Proposals list now contains only objects from the next hierarchy level
                        - Fixed autocompletion for SELECT statements with table hints for SQL Server
                    - Fixed the issue where the old result set tab didn't close when switching between multiple and single tab modes
                    - Fixed a stack overflow error that occurred when a user tried to execute a script for an open result set with row coloring
                    - When an error occurs, the last executed query is now displayed next to the error message
                    - Fixed an exception that appeared while typing
                - AI assistant: Fixed syntax issues in queries generated by Azure Open AI
                - Data Editor:
                    - Added hints for geometries with SRID and for timestamps with time zones
                    - Added the ability to configure hint visibility for a table or a datasource
                    - Hints presentation was enhanced
                    - Added backslash escaping when generating scripts
                    - Added an option to disable the dictionary view (set "Maximum amount of elements" to 0)
                    - Fixed freezing issues when pasting big number of rows or when performing find/replace
                    - Added an option to save XML and JSON files in compressed format
                    - Fixed data editor filters for commom table expressions
                - Miscellaneous: Added the ability to create bookmarks from the context menu of object tabs
                - Databases:
                    - Cloudberry driver was added
                    - CUBRID: Fixed view name generation in DDL (thanks to @longhaseng52)
                    - MySQL:
                        - USAGE privilege is now hidden if any other privilege has been granted
                        - Fixed loading of DBA privileges
                    - PostgreSQL:  Fixed the display of infinity for date values
- Key: ReleaseNotesUrl
  Value: https://github.com/dbeaver/dbeaver/releases/tag/24.3.3
Version: 24.3.3
ReleaseTime: 2025-01-19T16:50:33.0000000Z
