Installer:
- Architecture: x64
  InstallerUrl: https://github.com/cli/cli/releases/download/v2.46.0/gh_2.46.0_windows_amd64.msi
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    What's Changed
    - remove repetitive word by @cuinix in https://github.com/cli/cli/pull/8795
    - fixed doc string by @gregsmi in https://github.com/cli/cli/pull/8797
    - feat: consistent issue and PR owner/repo#number in various prompt by @nobe4 in https://github.com/cli/cli/pull/8778
    - build(deps): bump google.golang.org/protobuf from 1.30.0 to 1.33.0 by @dependabot in https://github.com/cli/cli/pull/8811
    - feat: support dry-run in gh pr create by @v1v in https://github.com/cli/cli/pull/8376
    - Fix the description of gh release upload by @malor in https://github.com/cli/cli/pull/8834
    - Bump go-keyring to fix race condition by @williammartin in https://github.com/cli/cli/pull/8833
    - Gh docs multiple accounts by @jsoref in https://github.com/cli/cli/pull/8838
    - Document auth switch behaviour for two or more accounts by @williammartin in https://github.com/cli/cli/pull/8839
    - Document run watch and view not supporting fine grained PATs by @williammartin in https://github.com/cli/cli/pull/8843
    - build(deps): bump github.com/cpuguy83/go-md2man/v2 from 2.0.3 to 2.0.4 by @dependabot in https://github.com/cli/cli/pull/8844
    - Feat draft issue id by @yasunori0418 in https://github.com/cli/cli/pull/8754
    New Contributors
    - @cuinix made their first contribution in https://github.com/cli/cli/pull/8795
    - @gregsmi made their first contribution in https://github.com/cli/cli/pull/8797
    - @nobe4 made their first contribution in https://github.com/cli/cli/pull/8778
    - @malor made their first contribution in https://github.com/cli/cli/pull/8834
    - @yasunori0418 made their first contribution in https://github.com/cli/cli/pull/8754
    Full Changelog: https://github.com/cli/cli/compare/v2.45.0...v2.46.0
- Key: ReleaseNotesUrl
  Value: https://github.com/cli/cli/releases/tag/v2.46.0
Version: 2.46.0
ReleaseTime: 2024-03-20T17:08:24.0000000Z
