Installer:
- Architecture: x64
  InstallerUrl: https://github.com/cli/cli/releases/download/v2.48.0/gh_2.48.0_windows_amd64.msi
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    What's Changed
    - Fix panic when running gh repo rename by @babakks in https://github.com/cli/cli/pull/8906
    - build(deps): bump google.golang.org/grpc from 1.61.1 to 1.61.2 by @dependabot in https://github.com/cli/cli/pull/8925
    - Add codeowners entry for the GitHub TUF root included in the attestation command set by @malancas in https://github.com/cli/cli/pull/8919
    - Fix parsing IPv6 remote URLs by @babakks in https://github.com/cli/cli/pull/8893
    - Fixed gh pr lock/unlock not working when URL is passed by @t4kamura in https://github.com/cli/cli/pull/8837
    - Anchor the log filename to the start by @zdrve in https://github.com/cli/cli/pull/8882
    - Create stronger run log cache abstraction by @williammartin in https://github.com/cli/cli/pull/8931
    - Remove naked returns from git ParseURL by @williammartin in https://github.com/cli/cli/pull/8929
    - Fix api cache test by @williammartin in https://github.com/cli/cli/pull/8932
    - Ensure run log cache creates cache dir if it doesn't exist by @williammartin in https://github.com/cli/cli/pull/8944
    - Close zip file in run view tests by @williammartin in https://github.com/cli/cli/pull/8945
    - Include numSelectedRepos in JSON output of gh secret list by @babakks in https://github.com/cli/cli/pull/8899
    - allow multiple items in nested array by @Ebonsignori in https://github.com/cli/cli/pull/8762
    - Fix attestation cmd offline unit test failure by @malancas in https://github.com/cli/cli/pull/8933
    - Add support to attestation command for more predicate types. by @steiza in https://github.com/cli/cli/pull/8949
    - Tidy go.mod by @matthewhughes934 in https://github.com/cli/cli/pull/8958
    - Fix cache contention in Go CI jobs by @matthewhughes934 in https://github.com/cli/cli/pull/8957
    - Add --skip-ssh-key option to gh auth login command by @babakks in https://github.com/cli/cli/pull/8935
    - Fix go directive in go.mod by @matthewhughes934 in https://github.com/cli/cli/pull/8956
    - Update install_linux.md by @richterdavid in https://github.com/cli/cli/pull/8950
    - Merge JSON responses from gh api by @heaths in https://github.com/cli/cli/pull/8620
    New Contributors
    - @babakks made their first contribution in https://github.com/cli/cli/pull/8906
    - @t4kamura made their first contribution in https://github.com/cli/cli/pull/8837
    - @zdrve made their first contribution in https://github.com/cli/cli/pull/8882
    - @Ebonsignori made their first contribution in https://github.com/cli/cli/pull/8762
    - @matthewhughes934 made their first contribution in https://github.com/cli/cli/pull/8958
    - @richterdavid made their first contribution in https://github.com/cli/cli/pull/8950
    Full Changelog: https://github.com/cli/cli/compare/v2.47.0...v2.48.0
- Key: ReleaseNotesUrl
  Value: https://github.com/cli/cli/releases/tag/v2.48.0
Version: 2.48.0
ReleaseTime: 2024-04-17T10:04:56.0000000Z
