Installer:
- Architecture: x64
  InstallerUrl: https://github.com/cli/cli/releases/download/v2.49.2/gh_2.49.2_windows_amd64.msi
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    What's Changed
    - Improve run list doc with available --json fields by @babakks in https://github.com/cli/cli/pull/8934
    - Fix typos by @szepeviktor in https://github.com/cli/cli/pull/9068
    - Move config interfaces into gh package by @williammartin in https://github.com/cli/cli/pull/9060
    - Creating doc to capture Codespace usage guidance by @andyfeller in https://github.com/cli/cli/pull/9066
    - Fix repo fork regression by @williammartin in https://github.com/cli/cli/pull/9063
    - Add --latest=false to gh release create docs by @kuzdogan in https://github.com/cli/cli/pull/8987
    - build(deps): bump github.com/sigstore/protobuf-specs from 0.3.1 to 0.3.2 by @dependabot in https://github.com/cli/cli/pull/9075
    New Contributors
    - @szepeviktor made their first contribution in https://github.com/cli/cli/pull/9068
    - @kuzdogan made their first contribution in https://github.com/cli/cli/pull/8987
    Full Changelog: https://github.com/cli/cli/compare/v2.49.1...v2.49.2
- Key: ReleaseNotesUrl
  Value: https://github.com/cli/cli/releases/tag/v2.49.2
Version: 2.49.2
ReleaseTime: 2024-05-13T17:34:30.0000000Z
