Installer:
- Architecture: x64
  InstallerUrl: https://github.com/cli/cli/releases/download/v2.49.1/gh_2.49.1_windows_amd64.msi
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    What's Changed
    - Do not mutate headers when initialising tableprinter by @williammartin in https://github.com/cli/cli/pull/9033
    - Document relationship between host and active account by @williammartin in https://github.com/cli/cli/pull/9032
    - build(deps): bump golang.org/x/net from 0.22.0 to 0.23.0 by @dependabot in https://github.com/cli/cli/pull/9034
    - Run attestation command set integration tests separately by @malancas in https://github.com/cli/cli/pull/9035
    - Added support for jobs with long filenames by @shayn-orca in https://github.com/cli/cli/pull/8684
    - Fix unused params across project by @williammartin in https://github.com/cli/cli/pull/9059
    - Fix attestation verify source repository check bug by @malancas in https://github.com/cli/cli/pull/9053
    New Contributors
    - @shayn-orca made their first contribution in https://github.com/cli/cli/pull/8684
    Full Changelog: https://github.com/cli/cli/compare/v2.49.0...v2.49.1
- Key: ReleaseNotesUrl
  Value: https://github.com/cli/cli/releases/tag/v2.49.1
Version: 2.49.1
ReleaseTime: 2024-05-08T14:19:59.0000000Z
