Installer:
- Architecture: x64
  InstallerUrl: https://github.com/cli/cli/releases/download/v2.56.0/gh_2.56.0_windows_amd64.msi
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    What's Changed
    - Always print URL scheme to stdout by @heaths in https://github.com/cli/cli/pull/9471
    - Quote repo names consistently in gh repo sync stdout by @muzimuzhi in https://github.com/cli/cli/pull/9491
    - Fetch bundle from OCI registry for verify by @ejahnGithub in https://github.com/cli/cli/pull/9421
    - Remove Internal from gh repo create prompt when owner is not an org by @jtmcg in https://github.com/cli/cli/pull/9465
    - Drop surplus trailing space char in flag names in web by @muzimuzhi in https://github.com/cli/cli/pull/9495
    - fix the trimming of log filenames for gh run view by @benebsiny in https://github.com/cli/cli/pull/9482
    - "offline" verification using the bundle of attestations without any additional handling of the file by @aryanbhosale in https://github.com/cli/cli/pull/9523
    - build(deps): bump actions/attest-build-provenance from 1.4.1 to 1.4.2 by @dependabot in https://github.com/cli/cli/pull/9518
    - Fix doc typo for repo sync by @muzimuzhi in https://github.com/cli/cli/pull/9509
    - Correct the help message for -F by @Goooler in https://github.com/cli/cli/pull/9525
    - chore: fix some function names by @crystalstall in https://github.com/cli/cli/pull/9555
    - verify 2nd artifact without swapping order by @aryanbhosale in https://github.com/cli/cli/pull/9532
    - gh attestation verify handles empty JSONL files by @malancas in https://github.com/cli/cli/pull/9541
    - Enhance Linux installation docs to redirect users to GPG renewal issue, better troubleshooting support by @andyfeller in https://github.com/cli/cli/pull/9573
    - Upgrade sigstore-go to v0.6.1 by @codysoyland in https://github.com/cli/cli/pull/9566
    - Check for nil values to prevent nil dereference panic by @codysoyland in https://github.com/cli/cli/pull/9578
    - build(deps): bump actions/attest-build-provenance from 1.4.2 to 1.4.3 by @dependabot in https://github.com/cli/cli/pull/9575
    New Contributors
    - @aryanbhosale made their first contribution in https://github.com/cli/cli/pull/9523
    - @Goooler made their first contribution in https://github.com/cli/cli/pull/9525
    - @crystalstall made their first contribution in https://github.com/cli/cli/pull/9555
    Full Changelog: https://github.com/cli/cli/compare/v2.55.0...v2.56.0
- Key: ReleaseNotesUrl
  Value: https://github.com/cli/cli/releases/tag/v2.56.0
Version: 2.56.0
ReleaseTime: 2024-09-09T12:22:00.0000000Z
