Installer:
- Architecture: x64
  InstallerUrl: https://github.com/cli/cli/releases/download/v2.59.0/gh_2.59.0_windows_amd64.msi
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    What's Changed
    - Allow community submitted design work by @BagToad in https://github.com/cli/cli/pull/9683
    - Improve SECURITY.md with expectations for privately reported vulnerabilities by @BagToad in https://github.com/cli/cli/pull/9687
    - Emit a log message when extension installation falls back to a darwin-amd64 binary on an Apple Silicon macOS device by @timrogers in https://github.com/cli/cli/pull/9650
    - Print the login URL even when opening a browser by @ulfjack in https://github.com/cli/cli/pull/7091
    - configurable maxwidth for markdown WithWrap() by @smemsh in https://github.com/cli/cli/pull/9626
    - Handle errors when parsing hostname in auth flow by @BagToad in https://github.com/cli/cli/pull/9729
    - Add repo license list/view and repo gitignore list/view by @BagToad in https://github.com/cli/cli/pull/9721
    - Introduce testscript acceptance tests generally, and for the PR command specifically by @williammartin in https://github.com/cli/cli/pull/9745
    - Support GH_ACCEPTANCE_SCRIPT env var to target a single script by @williammartin in https://github.com/cli/cli/pull/9756
    - Ensure Acceptance defer failures are debuggable by @williammartin in https://github.com/cli/cli/pull/9754
    - Add acceptance task to makefile by @williammartin in https://github.com/cli/cli/pull/9748
    - Add Acceptance tests for issue command by @williammartin in https://github.com/cli/cli/pull/9757
    - Update IsEnterprise and IsTenancy for orthogonality using go-gh by @jtmcg in https://github.com/cli/cli/pull/9755
    - Supporting filtering on gist list by @heaths in https://github.com/cli/cli/pull/9728
    New Contributors
    - @ulfjack made their first contribution in https://github.com/cli/cli/pull/7091
    - @smemsh made their first contribution in https://github.com/cli/cli/pull/9626
    Full Changelog: https://github.com/cli/cli/compare/v2.58.0...v2.59.0
- Key: ReleaseNotesUrl
  Value: https://github.com/cli/cli/releases/tag/v2.59.0
Version: 2.59.0
ReleaseTime: 2024-10-16T12:28:09.0000000Z
