Installer:
- Architecture: x64
  InstallerUrl: https://github.com/yt-dlp/yt-dlp/releases/download/2024.11.04/yt-dlp.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    A description of the various files is in the README

    Important changes
    - Beginning with this release, yt-dlp's Python dependencies must be installed using the default group If you're installing yt-dlp with pip/pipx or requiring yt-dlp in your own Python project, you'll need to specify yt-dlp[default] if you want to also install yt-dlp's optional dependencies (which were previously included by default). Read more
    - The minimum required Python version has been raised to 3.9 Python 3.8 reached its end-of-life on 2024.10.07, and yt-dlp has now removed support for it. As an unfortunate side effect, the official yt-dlp.exe and yt-dlp_x86.exe binaries are no longer supported on Windows 7. Read more
    Changelog
    Core changes
    - Allow thumbnails with .jpe extension (#11408) by bashonly
    - Expand paths in --plugin-dirs (#11334) by bashonly
    - Fix --netrc empty string parsing for Python <=3.10 (#11414) by bashonly, Grub4K
    - Populate format sorting fields before dependent fields (#11353) by Grub4K
    - Prioritize AV1 (#11153) by seproDev
    - Remove Python 3.8 support (#11321) by bashonly
    - aes: Fix GCM pad length calculation (#11438) by seproDev
    - cookies: Support chrome table version 24 (#11425) by kesor, seproDev
    - utils
      - Allow partial application for more functions (#11391) by bashonly, Grub4K (With fixes in 422195e by Grub4K)
      - Fix find_element by class (#11402) by bashonly
      - Fix and improve find_element and find_elements (#11443) by bashonly, Grub4K
    Extractor changes
    - Resolve language to ISO639-2 for ISM formats (#11359) by bashonly
    - ardmediathek: Extract chapters (#11442) by iw0nderhow
    - bfmtv: Fix extractors (#11444) by seproDev
    - bluesky: Add extractor (#11055) by MellowKyler, seproDev
    - ccma: Support new 3cat.cat domain (#11222) by JoseAngelB
    - chzzk: video: Fix extraction (#11228) by hui1601
    - cnn: Fix extractor (#10185) by kylegustavo, seproDev
    - dailymotion
      - Improve embed extraction (#10843) by bashonly, pzhlkj6612
      - Support shortened URLs (#11374) by bashonly, seproDev
    - facebook: Fix formats extraction (#11343) by kclauhk
    - generic: Do not impersonate by default (#11336) by bashonly
    - nfl: Fix extractors (#11409) by bashonly
    - niconicouser: Fix extractor (#11324) by Wesley107772
    - soundcloud: Extract artists (#11377) by seproDev
    - tumblr: Support more URLs (#6057) by selfisekai, seproDev
    - twitter: Remove cookies migration workaround (#11392) by bashonly
    - vimeo: Fix API retries (#11351) by bashonly
    - yle_areena: Support live events (#11358) by bashonly, CounterPillow
    - youtube: Adjust OAuth refresh token handling (#11414) by bashonly
    Misc. changes
    - build
      - Disable attestations for trusted publishing (#11418) by bashonly
      - Move optional dependencies to the default group (#11255) by bashonly
      - Use Ubuntu 20.04 and Python 3.9 for Linux ARM builds (#8638) by bashonly
    - cleanup
      - Miscellaneous
        - ea9e35d by bashonly
        - c998238 by bashonly, KBelmin
        - 197d0b0 by avagordon01, bashonly, grqz, Grub4K, seproDev
    - devscripts: make_changelog: Parse full commit message for fixes (#11366) by bashonly, Grub4K
- Key: ReleaseNotesUrl
  Value: https://github.com/yt-dlp/yt-dlp/releases/tag/2024.11.04
Version: 2024.11.04
ReleaseTime: 2024-11-04T00:51:21.0000000Z
