Installer:
- Architecture: x64
  InstallerUrl: https://github.com/pinokiocomputer/pinokio/releases/download/3.3.29/Pinokio-3.3.29-win32.zip
  NestedInstallerFiles:
  - RelativeFilePath: Pinokio Setup 3.3.29.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Sorry for the frequent releases, but it's important that we get this out asap so here we go.
    One other edge case we discovered with Visual Studio Build Tools is, often VS buildtools 2022 FAILS when used during building wheels.
    If you search online, the recommendation is to "downgrade" to 2019, so if we really wanted to have a robust system, Pinokio should enforce visual studio build tools 2019 no matter what. What this means is:
    1. If no visual studio installed => Install visual studio build tools 2019
    2. if visual studio build tools 2022 installed => install visual studio build tools 2019 => now you have both 2019 and 2022 (but pinokio will always use 2019 since 2022 often doesn't work and we can't risk that)
    3. If Visual Studio is installed (2022, 2019, etc) => Also install visual studio build tools 2019 => now you have normal visual studio and visual studio build tools 2019
    Going forward, Pinokio will always make the user install Visual Studio Build Tools 2019.
- Key: ReleaseNotesUrl
  Value: https://github.com/pinokiocomputer/pinokio/releases/tag/3.3.29
Version: 3.3.29
ReleaseTime: 2025-01-25T21:11:13.0000000Z
