Installer:
- Architecture: x64
  InstallerUrl: https://github.com/pinokiocomputer/pinokio/releases/download/2.15.1/Pinokio-2.15.1-win32.zip
  NestedInstallerFiles:
  - RelativeFilePath: Pinokio Setup 2.15.1.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Previously when you shut down Pinokio before shutting down apps, some of the remaining app processes may stick around, causing issues such as:
    1. Keep consuming memory even when they all should be shut down
    2. Sometimes you get "uvicorn" related errors saying the process is still running (This is because when you closed Pinokio last time, the uvicorn server inside pinokio kept sticking around even though it should have been shut down along with Pinokio)
    3. Sometimes you can't delete folders because the folders are locked. All because the process associated with those folders are still running
    Basically this update is a critical fix if you want to use Pinokio in a stable way. No other features have been touched, just this bug fixed, so no reason not to upgrade.
- Key: ReleaseNotesUrl
  Value: https://github.com/pinokiocomputer/pinokio/releases/tag/2.15.1
Version: 2.15.1
ReleaseTime: 2024-09-17T15:03:29.0000000Z
