Installer:
- Architecture: x64
  InstallerUrl: https://github.com/pinokiocomputer/pinokio/releases/download/3.3.25/Pinokio-3.3.25-win32.zip
  NestedInstallerFiles:
  - RelativeFilePath: Pinokio Setup 3.3.25.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Windows Fix
    This release is mainly for Windows users. More specifically for apps that require building/compiling from source code.
    Visual Studio Build Tools and CUDA were not working properly on Windows. This didn't affect a lot of apps since many apps use prebuilt wheels. But some apps (such as 3D mesh generation AI apps) required building from source, and these apps were failing to install for many users.
    This updated fixes all of this.
    1. Visual Studio Handling: instead of injecting environment variables manually, just use the official vcvarsall.bat right after conda activation.
    2. CUDA Handling: In case there's a globally installed CUDA that gets leaked in, remove those attributes so the base environment will use the CUDA installed inside the pinokio home environment
- Key: ReleaseNotesUrl
  Value: https://github.com/pinokiocomputer/pinokio/releases/tag/3.3.25
Version: 3.3.25
ReleaseTime: 2025-01-25T15:39:58.0000000Z
