Installer:
- Architecture: x64
  InstallerUrl: https://github.com/pinokiocomputer/pinokio/releases/download/3.6.0/Pinokio-3.6.0-win32.zip
  NestedInstallerFiles:
  - RelativeFilePath: Pinokio Setup 3.6.0.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Lots of Bug Fixes
    Again fixed a lot of issues based on bug reports since 3.3
    Added in 3.5
    1. On Windows, give full write permission to ~/pinokio just to make sure we NEVER run into any EACCESS errors.
    2. Set CUDA_HOME to point to ~/pinokio/bin/miniconda
    3. build attribute added to shell.run: When "build": true, all the Visual Studio Build Tools related environment variables are injected into the shell.run session by running vcvarsall.bat.
    4. Script schema updated to <=3.6.0
    Example:
    {
      "method": "shell.run",
      "parrams": {
        "message": "python setup.py install",
        "build": true,
        "venv": "env"
      }
    }
    Added in 3.5
    1. Port 42000: all pinokio instances will now use port 42000 regardless of platform.
    2. UV Fix: In some cases, using the automatic python download feature of UV was not working properly because UV for some reason uses system python instead of managed python, which loses isolation. Now UV uses totally isolated managed python, which works on any OS and any system.
    3. visual studio installer fix
    4. Fix Networking issues: In some cases, having certain environment variables set messes up network connections, so Pinokio makes sure to ignore them
    5. Start logging immediately after the app starts (instead of after everything is initialized): Because something could go wrong while initializing, and need to capture hose too.
- Key: ReleaseNotesUrl
  Value: https://github.com/pinokiocomputer/pinokio/releases/tag/3.6.0
Version: 3.6.0
ReleaseTime: 2025-02-01T14:42:48.0000000Z
