Installer:
- Architecture: x64
  InstallerUrl: https://github.com/pinokiocomputer/pinokio/releases/download/2.14.0/Pinokio-2.14.0-win32.zip
  NestedInstallerFiles:
  - RelativeFilePath: Pinokio Setup 2.14.0.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Windows 24H2
    Pinokio finally supports Windows 24H2 (Windows Insider Preview Canary + Dev + Beta + Release Candidate). Microsoft will soon roll out Windows 24H2, which breaks how shells work, which breaks all shell manipulation methods in Pinokio.
    With Pinokio 2.2.0, the shell engine has been updated to work correctly on 24H2. This is a REQUIRED update.

    Open in File Explorer

    You can open any files and folders in a file explorer by appending ?fs to any URI in the pinokio.js file. Example:
    // pinokio.js
    module.exports = {
      version: "2.1",
      title: "test",
      description: "description",
      menu: [{
        text: "Open app folder",
        href: "app?fs"
      }]
    }

    Navigation Buttons
    Based on feedback, the back/forward navigation buttons are back. Now you can navigate back and forth between pages instead of having to go back to home and come back.
- Key: ReleaseNotesUrl
  Value: https://github.com/pinokiocomputer/pinokio/releases/tag/2.14.0
Version: 2.14.0
ReleaseTime: 2024-08-29T20:55:52.0000000Z
