Installer:
- Architecture: x64
  InstallerUrl: https://github.com/taers232c/GAMADV-XTD3/releases/download/v6.72.09/gamadv-xtd3-6.72.09-windows-x86_64.msi
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Scroll to bottom of page for installation/downloads
    Latest updates
    6. 72.09
    Updated countsonly option of gam <UserTypeEntity> print|show notes to additionally display the total number of notes.
    6. 72.08
    Added option countsonly to gam <UserTypeEntity> print|show notes that displays the number of notes a user owns and the number of notes a user can edit.
    6. 72.07
    Updated commands that send emails to not downshift 'First Last<firstlast@domain.com>' to 'first last<firstlast@domain.com>'.
    6. 72.06
    Updated the following commands to properly handle emailaddress lists containing addresses of the form: 'First Last<firstlast@domain.com>'.
    gam <UserTypeEntity> sendemail recipient|to <RecipientEntity> [cc <RecipientEntity>] [bcc <RecipientEntity>] [singlemessage]
    gam create|update user ... notify <EmailAddressList>
    6. 72.05
    Cleaned up code for all commands that display Chat objects.
    6. 72.04
    Added commands to display Chat events.
    - See: https://github.com/taers232c/GAMADV-XTD3/wiki/Users-Chat#display-chat-events
    6. 72.03
    Fixed bug in gam <UserTypeEntity> create chatspace that caused a trap.
    6. 72.02
    Updated gam delete admin <RoleAssignmentId> to handle the following error that occurs when <RoleAssignmentId> references a user that has been deleted.
    ERROR: 404: resourceNotFound - Does not exist
    6. 72.01
    Improved commands to display drive file comments.
    6. 72.00
    Added commands to display drive file comments.
    - See: https://github.com/taers232c/GAMADV-XTD3/wiki/Users-Drive-Comments
    Installation
    If you are a first time Gam user:
    - https://github.com/taers232c/GAMADV-XTD3/wiki/How-to-Install-Advanced-GAM
    If you are updating your GAMADV-XTD3 version:
    - https://github.com/taers232c/GAMADV-XTD3/wiki/How-to-Update-Advanced-GAM
    If you are upgrading from standard Gam
    - https://github.com/taers232c/GAMADV-XTD3/wiki/How-to-Upgrade-from-Standard-GAM
    If you are upgrading from GAMADV-X or GAMADV-XTD
    - https://github.com/taers232c/GAMADV-XTD3/wiki/How-to-Upgrade-from-GAMADV-X-or-GAMADV-XTD
    sha256 hashes
    a043e534ab489a4496d576e44476e336d4f964ce1d4fe27a78910d516937d0af  gamadv-xtd3-6.72.09-linux-arm64-glibc2.23.tar.xz
    87f36cdb531dfa092b78eb66fdf0cb7b66cd94d30897047c1e102fe5d136956c  gamadv-xtd3-6.72.09-linux-arm64-glibc2.27.tar.xz
    82bf1bb339cfecb5c5674fe0a081cf815da307b4987cb6920e4eca4ef4c980ac  gamadv-xtd3-6.72.09-linux-arm64-glibc2.31.tar.xz
    8d3e8b17a384be155f6bc562c8d01ecdd435c928580cb9f1406b3f9395e69674  gamadv-xtd3-6.72.09-linux-x86_64-glibc2.19.tar.xz
    1d2f8f575c7bde6cba7b7418403ec6084a1452a34ad3cc397d29be45a51a37ad  gamadv-xtd3-6.72.09-linux-x86_64-glibc2.23.tar.xz
    048208de3199f8f61a0d3c8aa92d7372ac4abdebc6e770a29de357154138c63d  gamadv-xtd3-6.72.09-linux-x86_64-glibc2.27.tar.xz
    9331b9ac533ae74e2fafc6116efdd0b0d9de2a2039c9d60ef1549d9567cd7ea7  gamadv-xtd3-6.72.09-linux-x86_64-glibc2.31.tar.xz
    ab01340b7cae6fd85e5c47114e52a02ad1e1c72827f19b883afc8b18edb32e5a  gamadv-xtd3-6.72.09-linux-x86_64-glibc2.35.tar.xz
    b1fdc9307c8d0920b4afdb574239c57f8fa29469890c14b865dfd2e068b7754c  gamadv-xtd3-6.72.09-linux-x86_64-legacy.tar.xz
    934c87b3f7b937a6d0138aa066131c473b012a820268127762d49c44e3cd137a  gamadv-xtd3-6.72.09-macos-arm64.tar.xz
    1e5ba8cb72f71a58f9c61c4fc68d12e4010a7c0509f62fd2c4b921e160630128  gamadv-xtd3-6.72.09-macos-x86_64.tar.xz
    7deed203ed105632f9b9edb029bfa5ecf56bed405fbc0c54d6ff9ddfcfc6375b  gamadv-xtd3-6.72.09-windows-x86_64.msi
    876c4ff6e57ec417a2a86e6f9ee06cb2018cc036d8406f0e4a890252b810f886  gamadv-xtd3-6.72.09-windows-x86_64.zip
- Key: ReleaseNotesUrl
  Value: https://github.com/taers232c/GAMADV-XTD3/releases/tag/v6.72.09
Version: 6.72.09
ReleaseTime: 2024-04-05T01:14:56.0000000Z
