Installer:
- Architecture: x64
  InstallerUrl: https://github.com/taers232c/GAMADV-XTD3/releases/download/v6.71.15/gamadv-xtd3-6.71.15-windows-x86_64.msi
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Scroll to bottom of page for installation/downloads
    Latest updates
    6. 71.15
    Updated gam create project to handle the following error:
    ERROR: 403: permissionDenied - Authentication error: 7; Error Details: User not allowed to access GCP services.
    This error occurs when the Google Workspace admin or GCP project manager email address used in the command is in an OU where Google Cloud Platform is not enabled in Apps/Additional Google services.
    6. 71.14
    Added a command to update a Gmail label's settings by specifying it's ID rather than it's name.
    gam <UserTypeEntity> update labelid <LabelID> [name <String>]
            [messagelistvisibility hide|show] [labellistvisibility hide|show|showifunread]
            [backgroundcolor "<LabelColorHex>|<LabelBackgroundColorHex>|custom:<ColorHex>"]
            [textcolor "<LabelColorHex>|<LabelTextColorHex>|custom:<ColorHex>"]
    6. 71.13
    Updated <UserMultiAttribute>.location.buildingid <String> to allow non-validated building IDs by specifying nv: at the beginning of <String>; e.g., nv:Building X' sets the building ID to Building X`.
    6. 71.12
    Added option showmimetype category <MimeTypeNameList> to gam <UserTypeEntity> print|show filecounts|filelist|filetree
    <MimeTypeName> ::= application|audio|font|image|message|model|multipart|text|video
    <MimeTypeNameList> ::= "<MimeTypeName>(,<MimeTypeName>)*"

    gam user user@domain.com print filelist fields id,name,mimetype showmimetype prefixes audio,video
    Fix bug in gam <UserTypeEntity> info|show sheet <DriveFileEntity> that caused a trap.
    6. 71.11
    Added option addcsvdata <FieldName> <String> to gam print cros that adds additional columns of data to the CSV file output. Typically, you would read CSV file of device IDs/serial numbers to generate a CSV file of results and copy data from the input CSV to the outout CSV.
    6. 71.10
    Reverted change made in 6.71.09 to gam <UserTypeEntity> print filelist when showmimetype and filepath|fullpath were both specified. The change improved the performance when showmimetype selected a small number of files; the information for just those files was downloaded and then additional API calls were made to construct the file paths. However, if a large number of files were selected, the additional APIs calls decreased performance.
    Added option mimetypeinquery can be used when you expect the query to return a small number of files relative to the total number of files.
    6. 71.09
    Improved the performance of gam <UserTypeEntity> print filelist when showmimetype and filepath|fullpath are both specified.
    6. 71.08
    Added option oneitemperrow to 'gam print admins|adminroles` to have each of a roles privileges displayed on a separate row with all of the other admin/role fields. This produces a CSV file that can be used in subsequent commands without further script processing.
    6. 71.07
    Added command to upload changes to Google Docs.
    - See: https://github.com/taers232c/GAMADV-XTD3/wiki/Users-Drive-Files-Manage#upload-changes-to-google-documents
    6. 71.06
    Added additional error handling to Gmail Client Side Encryption commands.
    Added license product Education Endpoint Management
    - ProductID - 101049
    Added license SKU Endpoint Education Upgrade
    - ProductID - 101049
    - SKUID - 1010490001 | eeu
    6. 71.05
    Fixed a bug introduced in 6.71.00 that caused a trap in gam <UserTypeEntity> print filelist.
    Added option tdfrom <EmailAddress> to <ToDriveAttribute> that causes GAM to use <EmailAddress> as the from address in all emails sent. By default, the from address is the Google Workspace Admin in gam oauth info.o
    6. 71.04
    Updated gam <UserTypeEntity> create|update cseidentity to accept either of the following key pair options:
    - primarykeypairid <KeyPairID> - The configuration of a CSE identity that uses the same key pair for signing and encryption.
    - signingkeypairid <KeyPairID> encryptionkeypairid <KeyPairID> - The configuration of a CSE identity that uses different key pairs for signing and encryption.
    Updated CSV output row sorting to avoid a trap that occurred when a row was missing one of the sort fields.
    6. 71.03
    Added option tdalert <EmailAddress> to <ToDriveAttribute>. When a todrive file is created or updated, GAM will send notification emails to all tdalert <EmailAddress> users if tdnotify is true. <EmailAddress> must be valid within your Google Workspace.
    6. 71.02
    Added additional error handling to Gmail Client Side Encryption commands.
    6. 71.01
    Fixed bug in gam audit monitor create that caused a trap.
    6. 71.00
    Added csv_output_sort_headers string list variable to gam.cfg that causes GAM to sort CSV output rows by the column headers specified in the variable. The column headers are case insensitive and if column header does not appear in the CSV output, it is ignored.
    Added sortheaders <StringList> to redirect csv <FileName> that has the same effect as above.
    The sort keys specified in redirect csv ... sortheaders <StringList> take precedence over the values from gam.cfg.
    Added option tdsubject <String> to <ToDriveAttribute> that causes GAM to use <String> as the subject in all emails sent. In <String>, #file# will, be replaced by the file title and #sheet# will be replaced by the sheet/tab title. By default, the subject is the file title.
    Installation
    If you are a first time Gam user:
    - https://github.com/taers232c/GAMADV-XTD3/wiki/How-to-Install-Advanced-GAM
    If you are updating your GAMADV-XTD3 version:
    - https://github.com/taers232c/GAMADV-XTD3/wiki/How-to-Update-Advanced-GAM
    If you are upgrading from standard Gam
    - https://github.com/taers232c/GAMADV-XTD3/wiki/How-to-Upgrade-from-Standard-GAM
    If you are upgrading from GAMADV-X or GAMADV-XTD
    - https://github.com/taers232c/GAMADV-XTD3/wiki/How-to-Upgrade-from-GAMADV-X-or-GAMADV-XTD
    sha256 hashes
    64560d7d21f7fc1f5f9ee46bf6521b93b9fa0da813dc3615e9eb4efc38910e49  gamadv-xtd3-6.71.15-linux-arm64-glibc2.23.tar.xz
    2115fe8d1c9d66cb97388409e4b6d49e0a639c3d3abd6d80d24456216c955e6e  gamadv-xtd3-6.71.15-linux-arm64-glibc2.27.tar.xz
    c4ef2cb1f1d6167d97f54da504dcc7c4fce9fa3c8b578ce83f3cfedf119b7269  gamadv-xtd3-6.71.15-linux-arm64-glibc2.31.tar.xz
    fa98bc907ec0a3c84a5c24dc64bad57d6653a42d05247b717a5fbbc6216b49fa  gamadv-xtd3-6.71.15-linux-x86_64-glibc2.19.tar.xz
    7360e5f0b0418f08161c355f0da2253186be1b8346bae9e022069d2b79fa9f5f  gamadv-xtd3-6.71.15-linux-x86_64-glibc2.23.tar.xz
    e45558b375af3788a3a835a2b529337f16f38b0f10be6e98bc640e1ca5523199  gamadv-xtd3-6.71.15-linux-x86_64-glibc2.27.tar.xz
    91c40eeae17fbca8760d2bfdbc6ba65b45819eec129246efc4650c5346e30831  gamadv-xtd3-6.71.15-linux-x86_64-glibc2.31.tar.xz
    4a47a0b704e7cc4ba1fc0b3d28080b6c80f6b51d2340fdd3d0a219c5134f14a2  gamadv-xtd3-6.71.15-linux-x86_64-glibc2.35.tar.xz
    ad248b8477245509c2da10367e668ec3de43cd317d7fff145c4652c22dfa5f7a  gamadv-xtd3-6.71.15-linux-x86_64-legacy.tar.xz
    8b0b43fb9b752b9b95868e506606fd9afc005e05715b92e175903c164c75efc0  gamadv-xtd3-6.71.15-macos-arm64.tar.xz
    d2bc27b407d8e9506b5e3d4b8be7f7e6b759fe0f547fb33434261eda0acdc1d0  gamadv-xtd3-6.71.15-macos-x86_64.tar.xz
    fd03b35f5e3b383ae8c6a80172a4bc3ae01bb709f6bda350de78afd99e502391  gamadv-xtd3-6.71.15-windows-x86_64.msi
    e114acdc7f8f22d86ee758e48e1c60633bed14500a4119917c39cdf06ca5d592  gamadv-xtd3-6.71.15-windows-x86_64.zip
- Key: ReleaseNotesUrl
  Value: https://github.com/taers232c/GAMADV-XTD3/releases/tag/v6.71.15
Version: 6.71.15
ReleaseTime: 2024-03-14T00:20:32.0000000Z
