Installer:
- Architecture: x86
  InstallerUrl: https://github.com/AppFlowy-IO/AppFlowy/releases/download/0.6.3/AppFlowy-0.6.3-windows-x86_64.exe
- Architecture: x64
  InstallerUrl: https://github.com/AppFlowy-IO/AppFlowy/releases/download/0.6.3/AppFlowy-0.6.3-windows-x86_64.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Release Notes
    Version 0.6.3 - 07/08/2024
    New Features
    - Publish an AppFlowy document as a website / Share as a web page
- Key: ReleaseNotesUrl
  Value: https://github.com/AppFlowy-IO/AppFlowy/releases/tag/0.6.3
Version: 0.6.3
ReleaseTime: 2024-07-08T07:15:04.0000000Z
