Installer:
- Architecture: x86
  InstallerUrl: https://github.com/AppFlowy-IO/AppFlowy/releases/download/0.7.4/AppFlowy-0.7.4-windows-x86_64.exe
- Architecture: x64
  InstallerUrl: https://github.com/AppFlowy-IO/AppFlowy/releases/download/0.7.4/AppFlowy-0.7.4-windows-x86_64.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Release Notes
    Version 0.7.4 - 19/11/2024
    New Features
    - Support uploading WebP and BMP images
    - Support managing workspaces on mobile
    - Support adding toggle headings on mobile
    - Improve the AI chat page UI
    Bug Fixes
    - Optimized the workspace menu loading performance
    - Optimized tab switching performance
    - Fixed searching issues in Document page
- Key: ReleaseNotesUrl
  Value: https://github.com/AppFlowy-IO/AppFlowy/releases/tag/0.7.4
Version: 0.7.4
ReleaseTime: 2024-11-19T08:15:52.0000000Z
