Installer:
- Architecture: x86
  InstallerUrl: https://github.com/AppFlowy-IO/AppFlowy/releases/download/0.6.7/AppFlowy-0.6.7-windows-x86_64.exe
- Architecture: x64
  InstallerUrl: https://github.com/AppFlowy-IO/AppFlowy/releases/download/0.6.7/AppFlowy-0.6.7-windows-x86_64.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Release Notes
    Version 0.6.7 - 13/08/2024
    New Features
    - Redesigned the icon picker design on Desktop.
    - Redesigned the notification page on Mobile.
    Bug Fixes
    - Enhance the toolbar tooltip functionality on Desktop.
    - Enhance the slash menu user experience on Desktop.
    - Fixed the issue where list style overrides occurred during text pasting.
    - Fixed the issue where linking multiple databases in the same document could cause random loss of focus.
- Key: ReleaseNotesUrl
  Value: https://github.com/AppFlowy-IO/AppFlowy/releases/tag/0.6.7
Version: 0.6.7
ReleaseTime: 2024-08-13T07:14:25.0000000Z
