Installer:
- Architecture: x86
  InstallerUrl: https://github.com/AppFlowy-IO/AppFlowy/releases/download/0.7.3/AppFlowy-0.7.3-windows-x86_64.exe
- Architecture: x64
  InstallerUrl: https://github.com/AppFlowy-IO/AppFlowy/releases/download/0.7.3/AppFlowy-0.7.3-windows-x86_64.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Release Notes
    Version 0.7.3 - 07/11/2024
    New Features
    - Enable custom URLs for published pages
    - Support toggling headings
    - Create a subpage by typing in the document
    - Turn selected blocks into a subpage
    - Add a manual date picker for the Date property
    Bug Fixes
    - Fixed an issue where the workspace owner was unable to delete spaces created by others
    - Fixed cursor height inconsistencies with text height
    - Fixed editing issues in Kanban cards
    - Fixed an issue preventing images or files from being dropped into empty paragraphs
- Key: ReleaseNotesUrl
  Value: https://github.com/AppFlowy-IO/AppFlowy/releases/tag/0.7.3
Version: 0.7.3
ReleaseTime: 2024-11-08T03:42:42.0000000Z
