Installer:
- Architecture: x86
  InstallerUrl: https://github.com/AppFlowy-IO/AppFlowy/releases/download/0.5.6/AppFlowy-0.5.6-windows-x86_64.exe
- Architecture: x64
  InstallerUrl: https://github.com/AppFlowy-IO/AppFlowy/releases/download/0.5.6/AppFlowy-0.5.6-windows-x86_64.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Release Notes
    Version 0.5.6 - 05/27/2024
    New Features
    - Added support for creating multiple workspaces.
    - Included support for inviting members into your workspace.
    - Optimized document page style for mobile, enabling changing font size and line height.
    - Implemented support for opening rows as full pages.
    Bug Fixes
    - Resolved issue with setting background color for table blocks.
    - Adjusted toolbar count for various screen sizes.
    - Implemented request for photo permission before uploading images.
    - Exported creation and last modification timestamps for cells to CSV.
- Key: ReleaseNotesUrl
  Value: https://github.com/AppFlowy-IO/AppFlowy/releases/tag/0.5.6
Version: 0.5.6
ReleaseTime: 2024-05-07T11:45:07.0000000Z
