Installer:
- Architecture: x86
  InstallerUrl: https://github.com/SteamDatabase/SteamTokenDumper/releases/download/2024.10.12/SteamTokenDumper-win-x86.zip
  NestedInstallerFiles:
  - RelativeFilePath: SteamTokenDumper.exe
- Architecture: x64
  InstallerUrl: https://github.com/SteamDatabase/SteamTokenDumper/releases/download/2024.10.12/SteamTokenDumper-win-x64.zip
  NestedInstallerFiles:
  - RelativeFilePath: SteamTokenDumper.exe
- Architecture: arm64
  InstallerUrl: https://github.com/SteamDatabase/SteamTokenDumper/releases/download/2024.10.12/SteamTokenDumper-win-arm64.zip
  NestedInstallerFiles:
  - RelativeFilePath: SteamTokenDumper.exe
Locale:
- Key: ReleaseNotesUrl
  Value: https://github.com/SteamDatabase/SteamTokenDumper/releases/tag/2024.10.12
Version: 2024.10.12
ReleaseTime: 2024-10-12T18:51:15.0000000Z
