Installer:
- Architecture: x64
  InstallerUrl: https://github.com/mullvad/mullvadvpn-app/releases/download/2024.1/MullvadVPN-2024.1.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    This release is for desktop only.
    Here is a list of all changes since last stable release 2023.6.
    Added
    - Add CLI support for applying patches to the settings with mullvad import-settings.
    - Add account UUID to verbose 'mullvad account get -v' output.
    - Respect OS prefer-reduced-motion setting.
    - Add CLI command for exporting settings patches: mullvad export-settings. Currently, it generates a patch containing all patchable settings, which only includes relay IP overrides.
    - Make mullvad status prints if lockdown mode is enabled when disconnected.
    - Add option to configure custom API access methods. Custom API access methods allows the user to circumvent censorship by proxying API traffic.
    - Add confirmation dialog when deleting a custom list.
    - Add support for custom SOCKS5 OpenVPN bridges running locally.
    Changed
    - CLI command mullvad relay set tunnel wireguard entry-location changed to mullvad relay set tunnel wireguard entry location, as the location subcommand can now be swapped for custom-list to select entry relays using a custom list.
    - Remove --location flag from mullvad status CLI. Location and IP will now always be printed (if available). mullvad status listen no longer prints location info.
    - Change CLI interface for custom SOCKS5 bridges as part of supporting bridges running locally.
    - Upgrade the background map to a new WebGL 3D map. This should both look better and be more performant.
    - Update Electron from 26.3.0 to 28.1.3.
    - Improve the "Connecting to system service"-view with information about the situation and troubleshooting tips.
    - Update support email address to new email address, support@mullvadvpn.net.
    Linux
    - Rename interface name from wg-mullvad to wg0-mullvad.
    - Enable quantum resistant tunnels by default (when set to auto). On other platforms, auto still always means the same thing as off.
    Windows
    - Add information to error notification about an error that is often caused by an incompatibility with VMWare.
    Fixed
    - Validate that hostname matches correct server type for CLI commands mullvad relay set location, mullvad bridge set location, and mullvad relay set tunnel wireguard entry location.
    - Fix connectivity issues that would occur when using quantum-resistant tunnels with an incorrectly configured MTU.
    - Fix custom list name validation by not allowing empty names.
    - Fix map scaling issues when changing display scale settings and when running under Wayland on Linux.
    Linux
    - Prevent fragmentation when multihop is enabled by setting a default route MTU.
    - Fix Bash shell completions for subcommands in the CLI.
    - Fix out IP missing forever when am.i.mullvad.net returns error.
    macOS
    - Fix default route not being restored when disconnecting when the gateway was a link-local IPv6 address.
    - Fix app sometimes getting stuck in error state when the connection is unstable. This occurred when the default route was removed while connecting.
    - Improve multihop performance by preventing fragmentation in the tunnel. This is done by setting an MTU on the default route.
    - Fix bug that caused high CPU usage.
    - Fix bugs that caused the log to be filled with socket errors, by handling closed sockets gracefully.
- Key: ReleaseNotesUrl
  Value: https://github.com/mullvad/mullvadvpn-app/releases/tag/2024.1
Version: "2024.1"
ReleaseTime: 2024-03-21T15:01:18.0000000Z
