Installer:
- Architecture: x64
  InstallerUrl: https://github.com/mullvad/mullvadvpn-app/releases/download/2024.2/MullvadVPN-2024.2.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    This release is for desktop only.
    Here is a list of all changes since last stable release 2024.1.
    Added
    - Add automatic MTU detection for desktop platforms. This currently only uses information about dropped packets and does not take fragmentation into account.
    - Add ability to import server IP overrides in GUI.
    Changed
    - Change default obfuscation setting to auto.
    - Migrate obfuscation settings for existing users from off to auto.
    - Change default retry connection attempts.
    Fixed
    - Continual excessive attempts to update the API IP were made after testing access methods.
    - Fix pointless API access method rotations for concurrent requests.
    - Fix daemon rotating logs on startup even if another daemon is already running.
    - Fix missing redirect to out of time-view when running out of time.
    - Fix incorrectly showing "App lost contact with system service" notification on suspend.
    - Fix bug where the app would fail to select an existing relay in some scenarios, causing the user to wrongly end up in a blocked state.
    macOS
    - DNS was not properly restored in some cases when using custom DNS.
    Security
    macOS
    - Flush states on tunnel state changes. Previously, pre-existing connections could leak when internet sharing was enabled on a device.
    Windows
    - Update electron-builder to 24.13.3 to fix CVE-2024-27303, which enabled privilege escelation when running the installer.
- Key: ReleaseNotesUrl
  Value: https://github.com/mullvad/mullvadvpn-app/releases/tag/2024.2
Version: "2024.2"
ReleaseTime: 2024-04-29T07:10:15.0000000Z
