Installer:
- Architecture: x64
  InstallerUrl: https://github.com/mullvad/mullvadvpn-app/releases/download/2024.3/MullvadVPN-2024.3.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    This release is for desktop only.
    This release is identical to 2024.3-beta1.
    Here is a list of all changes since last stable release 2024.2.
    Added
    Windows
    - Add DAITA (Defence against AI-guided Traffic Analysis) setting. On supported servers, this makes website fingerprinting more difficult by sending random padding packets along with padding all packets to the same size.
    Changed
    - Don't fail to start daemon when the offline monitor fails to be initialized.
    Fixed
    Linux
    - Fix GUI not working on Ubuntu 24.04 by adding an AppArmor profile.
    - Service failed to start when IPv6 was disabled in the kernel.
- Key: ReleaseNotesUrl
  Value: https://github.com/mullvad/mullvadvpn-app/releases/tag/2024.3
Version: "2024.3"
ReleaseTime: 2024-05-15T12:49:08.0000000Z
