Installer:
- Architecture: x64
  InstallerUrl: https://github.com/Zettlr/Zettlr/releases/download/v3.0.5/Zettlr-3.0.5-x64.exe
- Architecture: x64
  InstallerUrl: https://github.com/Zettlr/Zettlr/releases/download/v3.0.5/Zettlr-3.0.5-x64.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Minor patch | Fixes Linux ARM | Drops support for macOS 10.13 & 10.14
    This update includes a critical security fix. We therefore recommend all users install this update as soon as possible. If you run macOS below version 10.15, which is no longer supported in Zettlr 3.0.5, please upgrade to Zettlr 3.0.4 by downloading this from GitHub Releases, which includes the security patch but still works on macOS 10.13 and 10.14 until you are able to update your macOS to 10.15 or higher.
    Immediately after v3.0.4, we decided to release a minor upgrade that bumps the underlying Electron framework to the most recent version. This will stop segmentation faults in Wayland environments and prevent the flagging of Zettlr in repositories such as AUR due to outdated dependencies.
    Dropping Support for macOS 10.13 and 10.14
    Due to Zettlr's underlying Electron framework dropping support for macOS 10.13 (High Sierra) and 10.14 (Mojave), Zettlr drops support for these operating systems as well. To continue to use Zettlr on a Mac, ensure to update to at least macOS 10.15 (Catalina).
    Linux ARM builds functionally again
    Since Zettlr v3.0.0, Linux users on ARM-machines had the issue that they could not run the app, as a dependency has been compiled for the wrong architecture. Thanks to efforts by @LaPingvino, this has now been finally fixed and you should be able to run the app again just fine on ARM computers with Linux.
    Changelog
    GUI and Functionality
    - Fix: Segmentation faults in Wayland environments (#4877)
    - Fix Linux ARM builds (#4910)
    Under the Hood
    - Update Electron from v25 to the latest available release (v28.2.1); this fixes segmentation fault issues in Wayland environments (#4877) and ensures that Zettlr keeps running a supported Electron version, which is especially pressing for the Arch Linux repository (see #4887; thanks to @alerque for bringing this to our attention), but also means that macOS 10.13 and 10.14 are no longer supported
    - Switched to Zig compiler to enable successful compilation for Linux ARM targets (#4910)
- Key: ReleaseNotesUrl
  Value: https://github.com/Zettlr/Zettlr/releases/tag/v3.0.5
Version: 3.0.5
ReleaseTime: 2024-02-07T10:44:01.0000000Z
