Installer:
- Architecture: x64
  InstallerUrl: https://github.com/ONLYOFFICE/DesktopEditors/releases/download/v8.0.1/DesktopEditors_x64.exe
- Architecture: x64
  InstallerUrl: https://github.com/ONLYOFFICE/DesktopEditors/releases/download/v8.0.1/DesktopEditors_x64.msi
- Architecture: x86
  InstallerUrl: https://github.com/ONLYOFFICE/DesktopEditors/releases/download/v8.0.1/DesktopEditors_x86.exe
- Architecture: x86
  InstallerUrl: https://github.com/ONLYOFFICE/DesktopEditors/releases/download/v8.0.1/DesktopEditors_x86.msi
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: See changes at CHANGELOG.md
- Key: ReleaseNotesUrl
  Value: https://github.com/ONLYOFFICE/DesktopEditors/releases/tag/v8.0.1
Version: 8.0.1
ReleaseTime: 2024-02-26T12:16:42.0000000Z
