Installer:
- Architecture: x64
  InstallerUrl: https://github.com/Governikus/AusweisApp/releases/download/2.2.2/AusweisApp-2.2.2.msi
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Anwender
    - Visuelle Anpassungen und Optimierungen der grafischen Oberfläche.
    - Optimierung der Barrierearmut und Tastaturbedienbarkeit.
    Entwickler
    - Ergänzung der Android-ABIs armeabi-v7a und x86_64 zusätzlich zu arm64-v8a im SDK.
- Key: ReleaseNotesUrl
  Value: https://github.com/Governikus/AusweisApp/releases/tag/2.2.2
Version: 2.2.2
ReleaseTime: 2024-10-23T09:52:03.0000000Z
