Installer:
- Architecture: x86
  InstallerUrl: https://github.com/martinrotter/rssguard/releases/download/4.7.0/rssguard-4.7.0-f2d3203df-win10.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    OK, dear users. Over recent releases, many features were added and as you can see RSS Guard bug tracker is full of (semi) bug reports which need to be addressed. Therefore I must declare feature-freeze for at least three upcoming releases. No new features will be added in forthcoming future, because RSS Guard codebase must be de-bugged and stabilized first. I will keep my word this time and no feature requests will be implemented.
    Sole focus will be on fixing bugs and polish existing features and clean codebase. The other reason for this is also that lately my free time had become much much more limited for many reasons - family, other hobbies, work around house etc.
    Added:
    - Full article content can now be fetched with a single button. Button is placed in article viewer toolbar right next to "Reader mode" button. This feature (just as "reader mode" feature) requires Node.js installation. The feature works both for articles and for regular websites opened in embedded web browser.
    - Article now can be marked (upon selection) as read with delay or only manually. (#1017)
    - All RSS Guard plugins/services are now placed in their own library (DLL/SO/DYLIB) files and are loaded by main RSS Guard library dynamically. This means that unused services can now be removed from RSS Guard installation if not used by the user. Also it allows for a cleaner and slimmer common codebase. Refactoring of main RSS Guard library was also done and it is now more usable as regular dynamic-link library. I expect some regressions as this was HUGE change. Also, this change allows new potential interested people in writing new plugins easier as they now can just copy one of existing plugins and tweak for new service. Also this change now propagates to RSS Guard installer which allows you to only install plugins/services you want.
    - Application (Qt) style and icon theme now can be properly set to respect system style/icons and this setting is dynamic, meaning if you change system theme and restart RSS Guard, new theme is honored. (#1352)
    - Button to copy system/app information to "About..." dialog. (#1318)
    - All modal dialogs now remember their sizes forever. (#1336)
    Fixed:
    - Removed debugging forgotten code. (#1354)
    - "Cleanup" button in downloader was greyed out when it should not be. (#1350)
    - App crashes when changing notification sound. (#1317)
    - Built-in user-agent was updated. You can also supply your own user-agent, see rssguard.exe --help for more info.
- Key: ReleaseNotesUrl
  Value: https://github.com/martinrotter/rssguard/releases/tag/4.7.0
Version: 4.7.0
ReleaseTime: 2024-05-14T06:17:22.0000000Z
