Installer:
- Architecture: x64
  InstallerUrl: https://github.com/Ryujinx/release-channel-master/releases/download/1.1.1297/ryujinx-1.1.1297-win_x64.zip
  NestedInstallerFiles:
  - RelativeFilePath: publish/Ryujinx.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: For more information about this release please check out the official Changelog.
- Key: ReleaseNotesUrl
  Value: https://github.com/Ryujinx/release-channel-master/releases/tag/1.1.1297
Version: 1.1.1297
ReleaseTime: 2024-05-02T11:33:40.0000000Z
