Installer:
- Architecture: x64
  InstallerUrl: https://github.com/Ryujinx/release-channel-master/releases/download/1.1.1372/ryujinx-1.1.1372-win_x64.zip
  NestedInstallerFiles:
  - RelativeFilePath: publish/Ryujinx.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: For more information about this release please check out the official Changelog.
- Key: ReleaseNotesUrl
  Value: https://github.com/Ryujinx/release-channel-master/releases/tag/1.1.1372
Version: 1.1.1372
ReleaseTime: 2024-08-06T00:09:27.0000000Z
