Installer:
- Architecture: x64
  InstallerUrl: https://github.com/Ryujinx/release-channel-master/releases/download/1.1.1311/ryujinx-1.1.1311-win_x64.zip
  NestedInstallerFiles:
  - RelativeFilePath: publish/Ryujinx.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: For more information about this release please check out the official Changelog.
- Key: ReleaseNotesUrl
  Value: https://github.com/Ryujinx/release-channel-master/releases/tag/1.1.1311
Version: 1.1.1311
ReleaseTime: 2024-05-15T05:20:35.0000000Z
