Installer:
- Architecture: x64
  InstallerUrl: https://github.com/kovidgoyal/calibre/releases/download/v7.9.0/calibre-64bit-7.9.0.msi
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: Release version 7.9.0
- Key: ReleaseNotesUrl
  Value: https://github.com/kovidgoyal/calibre/releases/tag/v7.9.0
Version: 7.9.0
ReleaseTime: 2024-04-19T03:37:22.0000000Z
