Installer:
- Architecture: x64
  InstallerUrl: https://github.com/kovidgoyal/calibre/releases/download/v7.11.0/calibre-64bit-7.11.0.msi
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: Release version 7.11.0
- Key: ReleaseNotesUrl
  Value: https://github.com/kovidgoyal/calibre/releases/tag/v7.11.0
Version: 7.11.0
ReleaseTime: 2024-05-24T02:39:54.0000000Z
