Installer:
- Architecture: x64
  InstallerUrl: https://github.com/prefix-dev/pixi/releases/download/v0.24.2/pixi-x86_64-pc-windows-msvc.msi
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    📃 Details
    Documentation
    - Add readthedocs examples by @bollwyvl in #1423
    - Fix typo in project_configuration.md by @RaulPL in #1502
    Fixed
    - Too much shell variables in activation of pixi shell by @ruben-arts in #1507
- Key: ReleaseNotesUrl
  Value: https://github.com/prefix-dev/pixi/releases/tag/v0.24.2
Version: 0.24.2
ReleaseTime: 2024-06-14T15:40:02.0000000Z
