Installer:
- Architecture: x64
  InstallerUrl: https://github.com/prefix-dev/pixi/releases/download/v0.33.0/pixi-x86_64-pc-windows-msvc.msi
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    ✨ Highlights
    This is the first release with the new pixi global implementation. It's a full reimplementation of pixi global where it now uses a manifest file just like pixi projects. This way you can declare your environments and save them to a VCS.
    It also brings features like, adding dependencies to a global environment, and exposing multiple binaries from the same environment that are not part of the main installed packages.
    Test it out with:
    # Normal feature
    pixi global install ipython

    # New features
    pixi global install \
        --environment science \           # Defined the environment name
        --expose scipython=ipython \      # Expose binaries under custom names
        ipython scipy                     # Define multiple dependencies for one environment
    This should result in a manifest in $HOME/.pixi/manifests/pixi-global.toml:
    version = 1

    [envs.ipython]
    channels = ["conda-forge"]
    dependencies = { ipython = "*" }
    exposed = { ipython = "ipython", ipython3 = "ipython3" }

    [envs.science]
    channels = ["conda-forge"]
    dependencies = { ipython = "*", scipy = "*" }
    exposed = { scipython = "ipython" }
    📖 Documentation
    Checkout the updated documentation on this new feature:
    - Main documentation on this tag: https://pixi.sh/v0.33.0/
    - Global CLI documentation: https://pixi.sh/v0.33.0/reference/cli/#global
    - The implementation documentation: https://pixi.sh/v0.33.0/features/global_tools/
    - The initial design proposal: https://pixi.sh/v0.33.0/design_proposals/pixi_global_manifest/
- Key: ReleaseNotesUrl
  Value: https://github.com/prefix-dev/pixi/releases/tag/v0.33.0
Version: 0.33.0
ReleaseTime: 2024-10-16T09:31:16.0000000Z
