Installer:
- Architecture: x64
  InstallerUrl: https://github.com/prefix-dev/pixi/releases/download/v0.20.1/pixi-x86_64-pc-windows-msvc.msi
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    ✨ Highlights
    - Big improvements on the pypi-editable installs.
    📃 Details
    Fixed
    - Editable non-satisfiable by @baszalmstra in #1251
    - Satisfiability with pypi extras by @baszalmstra in #1253
    - Change global install activation script permission from 0o744 -> 0o755 by @zen-xu in #1250
    - Avoid creating Empty TOML tables by @olivier-lacroix in #1270
    - Uses the special-case uv path handling for both built and source by @tdejager in #1263
    - Modify test before attempting to write to .bash_profile in install.sh by @bruchim-cisco in #1267
    - Parse properly 'default' as environment Cli argument by @olivier-lacroix in #1247
    - Apply schema.json normalization, add to docs by @bollwyvl in #1265
    - Improve absolute path satisfiability by @tdejager in #1252
    - Improve parse deno error and make task a required field in the cli by @ruben-arts in #1260
    New Contributors
    - @bollwyvl made their first contribution in #1265
    - @bruchim-cisco made their first contribution in #1267
    - @zen-xu made their first contribution in #1250
    Full commit history
- Key: ReleaseNotesUrl
  Value: https://github.com/prefix-dev/pixi/releases/tag/v0.20.1
Version: 0.20.1
ReleaseTime: 2024-04-26T14:34:34.0000000Z
