Installer:
- Architecture: x64
  InstallerUrl: https://github.com/prefix-dev/pixi/releases/download/v0.32.0/pixi-x86_64-pc-windows-msvc.msi
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    ✨ Highlights
    The biggest fix in this PR is the move to the latest rattler as it came with some major bug fixes for macOS and Rust 1.81 compatibility.
    Changed
    - Correctly implement total ordering for dependency provider by @tdejager in rattler/#892
    Fixed
    - Fixed self-clobber issue when up/down grading packages by @wolfv in rattler/#893
    - Check environment name before returning not found print by @ruben-arts in #2198
    - Turn off symlink follow for task cache by @ruben-arts in #2209
- Key: ReleaseNotesUrl
  Value: https://github.com/prefix-dev/pixi/releases/tag/v0.32.0
Version: 0.32.0
ReleaseTime: 2024-10-08T06:11:50.0000000Z
