Installer:
- Architecture: x64
  InstallerUrl: https://github.com/prefix-dev/pixi/releases/download/v0.40.1/pixi-x86_64-pc-windows-msvc.msi
- Architecture: arm64
  InstallerUrl: https://github.com/prefix-dev/pixi/releases/download/v0.40.1/pixi-aarch64-pc-windows-msvc.msi
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Release Notes
    ✨ Highlights
    We've reverted the breaking change of the depends_on field from 0.40.0, replacing it with a warning.
    This release also brings a performance boost to our Windows and Linux-musl builds by using faster allocators. On the (holoviews) project, we measured a significant speedup:
    # Linux musl
    Summary
      pixi-0.40.1 list --no-install ran
       12.65 ± 0.46 times faster than pixi-0.40.0 list --no-install

    # Windows
      pixi-0.40.1 list --no-install ran
        1.66 ± 0.07 times faster than pixi-0.40.0 list --no-install
        1.67 ± 0.09 times faster than pixi-0.39.5 list --no-install
        2.10 ± 0.09 times faster than pixi-0.39.4 list --no-install
    Fixed
    - Pyproject entry-points by @atmorling in #2886
    - Print warning when pixi manifest is not parsed in pixi search by @pavelzw in #2889
    - Add deprecation notice for depends_on by @baszalmstra in #2891
    Performance
    - Use faster allocators by @baszalmstra in #2874
    Refactor
    - Add online_tests feature to control Internet use by @mgorny in #2881
    - Simplify repodata_gateway function by @olivier-lacroix in #1793
    - Spawn main entrypoint in box by @baszalmstra in #2892
    New Contributors
    - @atmorling made their first contribution in #2886
    - @mgorny made their first contribution in #2881
    Download pixi 0.40.1
    File Platform Checksum
    pixi-aarch64-apple-darwin.tar.gz Apple Silicon macOS checksum
    pixi-x86_64-apple-darwin.tar.gz Intel macOS checksum
    pixi-aarch64-pc-windows-msvc.zip ARM64 Windows checksum
    pixi-aarch64-pc-windows-msvc.msi ARM64 Windows checksum
    pixi-x86_64-pc-windows-msvc.zip x64 Windows checksum
    pixi-x86_64-pc-windows-msvc.msi x64 Windows checksum
    pixi-aarch64-unknown-linux-musl.tar.gz ARM64 MUSL Linux checksum
    pixi-x86_64-unknown-linux-musl.tar.gz x64 MUSL Linux checksum
- Key: ReleaseNotesUrl
  Value: https://github.com/prefix-dev/pixi/releases/tag/v0.40.1
Version: 0.40.1
ReleaseTime: 2025-01-14T14:55:51.0000000Z
