Installer:
- Architecture: x64
  InstallerUrl: https://github.com/prefix-dev/pixi/releases/download/v0.18.0/pixi-x86_64-pc-windows-msvc.msi
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    ✨ Highlights
    - This release adds support for pyproject.toml, now pixi reads from the [tool.pixi] table.
    - We now support editable PyPI dependencies, and PyPI source dependencies, including git, path, and url dependencies.
    [!TIP] These new features are part of the ongoing effort to make pixi more flexible, powerful, and comfortable for the python users. They are still in progress so expect more improvements on these features soon, so please report any issues you encounter and follow our next releases!
    📃 Details
    Added
    - Support for pyproject.toml by @olivier-lacroix in #999
    - Support for PyPI source dependencies by @tdejager in #985
    - Support for editable PyPI dependencies by @tdejager in #1044
    - Build pixi for windows arm by @baszalmstra in #1053
    Changed
    - XDG_CONFIG_HOME and XDG_CACHE_HOME compliance by @chawyehsu in #1050
    - Build pixi for windows arm by @baszalmstra in #1053
    - Platform literals by @baszalmstra in #1054
    - Fixed error in auth example (CLI docs) by @ytausch in #1076
    Documentation
    - Add lockfile update description in preparation for pixi update by @ruben-arts in #1073
    - zsh may be used for installation on macOS by @pya in #1091
    - Fix typo in pixi auth documentation by @ytausch in #1076
    Fixed
    - Test failure on riscv64 by @hack3ric in #1045
    - Validation test was testing on a wrong pixi.toml by @ruben-arts in #1056
    - Pixi list shows path and editable by @baszalmstra in #1100
    - Docs ci by @ruben-arts in #1074
    - Add error for unsupported pypi dependencies by @baszalmstra in #1052
    - Interactively delete environment when it was relocated by @baszalmstra in #1102
    - Allow solving for different platforms by @baszalmstra in #1101
    - Don't allow extra keys in pypi requirements by @baszalmstra in #1104
    - Solve when moving dependency from conda to pypi by @baszalmstra in #1099
    New Contributors
    - @pya made their first contribution in #1091
    - @ytausch made their first contribution in #1076
    - @hack3ric made their first contribution in #1045
    - @olivier-lacroix made their first contribution in #999
    - @henryiii made their first contribution in #1063
    Full commit history
- Key: ReleaseNotesUrl
  Value: https://github.com/prefix-dev/pixi/releases/tag/v0.18.0
Version: 0.18.0
ReleaseTime: 2024-04-03T06:05:25.0000000Z
