Installer:
- Architecture: x64
  InstallerUrl: https://github.com/prefix-dev/pixi/releases/download/v0.20.0/pixi-x86_64-pc-windows-msvc.msi
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    ✨ Highlights
    - We now support env variables in the task definition, these can also be used as default values for parameters in your task which you can overwrite with your shell's env variables. e.g. task = { cmd = "task to run", env = { VAR="value1", PATH="my/path:$PATH" } }
    - We made a big effort on fixing issues and improving documentation!
    📃 Details
    Added
    - Add env to the tasks to specify tasks specific environment variables by @wolfv in https://github.com/prefix-dev/pixi/pull/972
    Changed
    - Add --pyproject option to pixi init with a pyproject.toml by @olivier-lacroix in #1188
    - Upgrade to new uv version 0.1.32 by @tdejager in #1208
    Documentation
    - Document pixi.lock by @ruben-arts in #1209
    - Document channel priority definition by @ruben-arts in #1234
    - Add rust tutorial including openssl example by @ruben-arts in #1155
    - Add python tutorial to documentation by @tdejager in #1179
    - Add JupyterLab integration docs by @renan-r-santos in #1147
    - Add Windows support for PyCharm integration by @pavelzw in #1192
    - Setup_pixi for local pixi installation by @ytausch in #1181
    - Update pypi docs by @Hofer-Julian in #1215
    - Fix order of --no-deps when pip installing in editable mode by @glemaitre in #1220
    - Fix frozen documentation by @ruben-arts in #1167
    Fixed
    - Small typo in list cli by @tdejager in #1169
    - Issue with invalid solve group by @baszalmstra in #1190
    - Improve error on parsing lockfile by @ruben-arts in #1180
    - Replace _ with - when creating environments from features by @wolfv in #1203
    - Prevent duplicate direct dependencies in tree by @abkfenris in #1184
    - Use project root directory instead of task.working_directory for base dir when hashing by @wolfv in #1202
    - Do not leak env vars from bat scripts in cmd.exe by @wolfv in #1205
    - Make file globbing behave more as expected by @wolfv in #1204
    - Fix for using file::// in pyproject.toml dependencies by @tdejager in #1196
    - Improve pypi version conversion in pyproject.toml dependencies by @wolfv in #1201
    - Update to the latest rattler by @wolfv in #1235
    BREAKING
    - task = { cmd = "task to run", cwd = "folder", inputs = "input.txt", output = "output.txt"} Where input.txt and output.txt where previously in folder they are now relative the project root. This changed in: #1202
    - task = { cmd = "task to run", inputs = "input.txt"} previously searched for all input.txt files now only for the ones in the project root. This changed in: #1204
    New Contributors
    - @glemaitre made their first contribution in #1220
    Full commit history
- Key: ReleaseNotesUrl
  Value: https://github.com/prefix-dev/pixi/releases/tag/v0.20.0
Version: 0.20.0
ReleaseTime: 2024-04-19T19:06:05.0000000Z
