Installer:
- Architecture: x64
  InstallerUrl: https://github.com/prefix-dev/pixi/releases/download/v0.34.0/pixi-x86_64-pc-windows-msvc.msi
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    ✨ Highlights
    - pixi global install now takes a flag --with, inspired by uv tool install. If you only want to add dependencies without exposing them, you can now run pixi global install ipython --with numpy --with matplotlib
    - Improved the output of pixi global subcommands
    - Many bug fixes
    Added
    - Add timeouts by @Hofer-Julian in #2311
    Changed
    - Global update should add new executables by @nichmor in #2298
    - Add pixi global install --with by @Hofer-Julian in #2332
    Documentation
    - Document where pixi-global.toml can be found by @Hofer-Julian in #2304
    - Add ros noetic example by @ruben-arts in #2271
    - Add nichita and julian to CITATION.cff by @Hofer-Julian in #2327
    - Improve keyring documentation to use pixi global by @olivier-lacroix in #2318
    Fixed
    - pixi global upgrade-all error message by @Hofer-Julian in #2296
    - Select correct run environment by @ruben-arts in #2301
    - Adapt channels to work with newest rattler-build version by @Hofer-Julian in #2306
    - Hide obsolete commands in help page of pixi global by @chawyehsu in #2320
    - Typecheck all tests by @Hofer-Julian in #2328
    Refactor
    - Improve upload errors by @ruben-arts in #2303
    New Contributors
    - @gerlero made their first contribution in #2300
- Key: ReleaseNotesUrl
  Value: https://github.com/prefix-dev/pixi/releases/tag/v0.34.0
Version: 0.34.0
ReleaseTime: 2024-10-22T10:38:33.0000000Z
