Installer:
- Architecture: x64
  InstallerUrl: https://github.com/prefix-dev/pixi/releases/download/v0.39.0/pixi-x86_64-pc-windows-msvc.msi
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    ✨ Highlights
    - We now have a new concurrency configuration in the pixi.toml file. This allows you to set the number of concurrent solves or downloads that can be run at the same time.
    - We changed the way pixi searches for a pixi manifest. Where it was previously first considering the activated pixi shell, it will now search first in the current directory and its parent directories. more info
    - The lockfile format is changed to make it slightly smaller and support source dependencies.
    Added
    - Add concurrency configuration by @ruben-arts in #2569
    Changed
    - Add XDG_CONFIG_HOME/.config to search of pixi global manifest path by @hoxbro in #2547
    - Let pixi global sync collect errors rather than returning early by @Hofer-Julian in #2586
    - Allow configuring pypi insecure host by @zen-xu in #2521
    - Reorder manifest discovery logic by @Hofer-Julian in #2564
    Documentation
    - Improve pixi manifest by @Hofer-Julian in #2596
    Fixed
    - pixi global list failing for empty environments by @Hofer-Julian in #2571
    - Macos activation cargo vars by @ruben-arts in #2578
    - Trampoline without corresponding json breaking by @Hofer-Julian in #2576
    - Ensure pinning strategy is not affected by non-semver packages by @seowalex in #2580
    - Pypi installs happening every time by @tdejager in #2587
    - pixi global report formatting by @Hofer-Julian in #2595
    - Improve test speed and support win-arm64 by @baszalmstra in #2597
    - Update Task::Alias to return command description by @jjjermiah in #2607
    Refactor
    - Split install pypi into module and files by @tdejager in #2590
    - PyPI installation traits + deduplication by @tdejager in #2599
    Pixi build
    We've merged in the main pixi build feature branch. This is a big change but shouldn't have affected any of the current functionality. If you notice any issues, please let us know.
    It can be turned on by preview = "pixi-build" in your pixi.toml file. It's under heavy development so expect breaking changes in that feature for now.
    - Preview of pixi build and workspaces by @tdejager in #2250
    - Build recipe yaml directly by @wolfv in #2568
    New Contributors
    - @seowalex made their first contribution in #2580
- Key: ReleaseNotesUrl
  Value: https://github.com/prefix-dev/pixi/releases/tag/v0.39.0
Version: 0.39.0
ReleaseTime: 2024-12-02T13:01:54.0000000Z
