Installer:
- Architecture: x64
  InstallerUrl: https://github.com/prefix-dev/pixi/releases/download/v0.31.0/pixi-x86_64-pc-windows-msvc.msi
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    ✨ Highlights
    Thanks to our maintainer @baszamstra! He sped up the resolver for all cases we could think of in #2162 Check the result of times it takes to solve the environments in our test set:
    Added
    - Add nodefaults to imported conda envs by @ruben-arts in #2097
    - Add newline to .gitignore by @ruben-arts in #2095
    - Add --no-activation option to prevent env activation during global install/upgrade by @183amir in #1980
    - Add --priority arg to project channel add by @minrk in #2086
    Changed
    - Use pixi spec for conda environment yml by @ruben-arts in #2096
    - Follow symlinks while walking files by @0xbe7a in #2141
    Documentation
    - Community: add array-api-extra by @lucascolley in #2107
    - Add minimal constructor example by @bollwyvl in #2102
    - Add description for pixi update --json by @scottamain in #2160
    - Fixes backticks for doc strings by @rachfop in #2174
    Fixed
    - Sort exported conda explicit spec topologically by @synapticarbors in #2101
    - --import env_file breaks channel priority by @fecet in #2113
    - Allow exact yanked pypi packages by @nichmor in #2116
    - Check if files are same in self-update by @apoorvkh in #2132
    - get_or_insert_nested_table by @Hofer-Julian in #2167
    - Improve install.sh PATH handling and general robustness by @Arcitec in #2189
    - Output tasks on pixi run without input by @ruben-arts in #2193
    Performance
    - Significantly speed up conda resolution by @baszalmstra in #2162
    New Contributors
    - @Arcitec made their first contribution in #2189
    - @rachfop made their first contribution in #2174
    - @scottamain made their first contribution in #2160
    - @apoorvkh made their first contribution in #2132
    - @0xbe7a made their first contribution in #2141
    - @fecet made their first contribution in #2113
    - @minrk made their first contribution in #2086
    - @183amir made their first contribution in #1980
    - @lucascolley made their first contribution in #2107
- Key: ReleaseNotesUrl
  Value: https://github.com/prefix-dev/pixi/releases/tag/v0.31.0
Version: 0.31.0
ReleaseTime: 2024-10-03T14:49:12.0000000Z
