Installer:
- Architecture: x86
  InstallerUrl: https://github.com/rizinorg/rizin/releases/download/v0.7.3/rizin_installer-v0.7.3-x86.exe
- Architecture: x64
  InstallerUrl: https://github.com/rizinorg/rizin/releases/download/v0.7.3/rizin_installer-v0.7.3-x86_64.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: '- Roll back prepackaged XZ version to 5.2.9'
- Key: ReleaseNotesUrl
  Value: https://github.com/rizinorg/rizin/releases/tag/v0.7.3
Version: 0.7.3
ReleaseTime: 2024-04-14T02:16:24.0000000Z
