Installer:
- Architecture: x64
  InstallerUrl: https://github.com/Ryujinx/release-channel-master/releases/download/1.1.1393/test-ava-ryujinx-1.1.1393-win_x64.zip
  NestedInstallerFiles:
  - RelativeFilePath: publish/Ryujinx.Ava.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: For more information about this release please check out the official Changelog.
- Key: ReleaseNotesUrl
  Value: https://github.com/Ryujinx/release-channel-master/releases/tag/1.1.1393
Version: 1.1.1393
ReleaseTime: 2024-09-17T19:25:39.0000000Z
