Installer:
- Architecture: x64
  InstallerUrl: https://github.com/Ryujinx/release-channel-master/releases/download/1.1.1378/test-ava-ryujinx-1.1.1378-win_x64.zip
  NestedInstallerFiles:
  - RelativeFilePath: publish/Ryujinx.Ava.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: For more information about this release please check out the official Changelog.
- Key: ReleaseNotesUrl
  Value: https://github.com/Ryujinx/release-channel-master/releases/tag/1.1.1378
Version: 1.1.1378
ReleaseTime: 2024-08-20T23:49:31.0000000Z
