Installer:
- Architecture: x64
  InstallerUrl: https://github.com/Ryujinx/release-channel-master/releases/download/1.1.1359/test-ava-ryujinx-1.1.1359-win_x64.zip
  NestedInstallerFiles:
  - RelativeFilePath: publish/Ryujinx.Ava.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: For more information about this release please check out the official Changelog.
- Key: ReleaseNotesUrl
  Value: https://github.com/Ryujinx/release-channel-master/releases/tag/1.1.1359
Version: 1.1.1359
ReleaseTime: 2024-07-22T15:46:17.0000000Z
