Installer:
- Architecture: x64
  InstallerUrl: https://github.com/Ryujinx/release-channel-master/releases/download/1.1.1323/test-ava-ryujinx-1.1.1323-win_x64.zip
  NestedInstallerFiles:
  - RelativeFilePath: publish/Ryujinx.Ava.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: For more information about this release please check out the official Changelog.
- Key: ReleaseNotesUrl
  Value: https://github.com/Ryujinx/release-channel-master/releases/tag/1.1.1323
Version: 1.1.1323
ReleaseTime: 2024-05-26T16:30:31.0000000Z
