Installer:
- Architecture: x86
  InstallerUrl: https://github.com/avrdudes/avrdude/releases/download/v8.0/avrdude-v8.0-windows-x86.zip
- Architecture: x64
  InstallerUrl: https://github.com/avrdudes/avrdude/releases/download/v8.0/avrdude-v8.0-windows-x64.zip
- Architecture: arm64
  InstallerUrl: https://github.com/avrdudes/avrdude/releases/download/v8.0/avrdude-v8.0-windows-arm64.zip
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    See Release Notes for changes
    Preferred Windows binaries to use: avrdude-v8.0-windows-x64.zip --> Windows MSVC 64 bit avrdude-v8.0-windows-mingw-x64.zip --> Windows MSYS2 mingw 64 bit
    Static build binaries (*.tar.gz) are recommended for Arduino users. Take note they do not contain libserialport support due to the limitation of the crossbuild container.
    Notes for the avrdude Windows binaries (static linked to the dependency libraries) :
    1. MSVC build is recommended for most Windows users unless you hit known limitations (see below). The majority of users should download avrdude-v8.0-windows-x64.zip. In case one of limitations below is unacceptable you may want to download avrdude-v8.0-windows_mingw-x64.zip.
    2. Known limitation for the above MSVC build (avrdude-v8.0-windows-x64.zip, avrdude-v8.0-windows-x86.zip and avrdude-v8.0-windows-arm64.zip)
    - https://github.com/avrdudes/avrdude/issues/1552 (no libserialport support)
    - https://github.com/avrdudes/avrdude/issues/1253 (slow speed when using arduino-ft232r or similar programmer)
    - https://github.com/avrdudes/avrdude/issues/968 (not working with USB Composite Device programmer like USBASP with the FW from https://github.com/dioannidis/usbasp)
    - https://github.com/avrdudes/avrdude/discussions/1440 (no support of CH341A)
    3. Known limitation for the MSYS2 mingw build (avrdude-v8.0-windows_mingw-x64.zip, avrdude-v8.0-windows_mingw-clang-x64.zip and avrdude-v8.0-windows_mingw-ucrt-x64.zip)
    - You will have to use Zadig to switch the FTDI vendor driver if you use libftdi based programmer (eg: ft232h, ft2232h, arduino-ft232r)
    - https://github.com/avrdudes/avrdude/issues/1271 (timeout may be more likely to happen for urclock in terminal mode)
    Notes for the Linux binaries: Please use chmod u+x to make the binary executable. The Linux binaries are static linked to dependency libraries. They are provided as is and are expected to work for most Linux distros within the past 5 years. Please build from source in case the binaries do not work for you. You can also report the issue.
- Key: ReleaseNotesUrl
  Value: https://github.com/avrdudes/avrdude/releases/tag/v8.0
Version: "8.0"
ReleaseTime: 2024-08-24T21:24:31.0000000Z
