Installer:
- Architecture: x64
  InstallerUrl: https://github.com/tacitdynamics/foldersync-desktop-production/releases/download/1.2.0/foldersync-desktop-1.2.0-windows-amd64.zip
- Architecture: x64
  InstallerUrl: https://github.com/tacitdynamics/foldersync-desktop-production/releases/download/1.2.0/foldersync-desktop.exe
- Architecture: x64
  InstallerUrl: https://github.com/tacitdynamics/foldersync-desktop-production/releases/download/1.2.0/foldersync-desktop-1.2.0.x64.msix
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: FolderSync Desktop v1.2.0
- Key: ReleaseNotesUrl
  Value: https://github.com/tacitdynamics/foldersync-desktop-production/releases/tag/1.2.0
Version: 1.2.0
ReleaseTime: 2024-04-04T12:13:16.0000000Z
