Installer:
- Architecture: x64
  InstallerUrl: https://github.com/neovide/neovide/releases/download/0.14.0/neovide.msi
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    What's Changed
    The main highlights are:
    - Rounded floating windows;
    - Users now have the option to choose the mouse cursor icon;
    - Apple code signing and notarization to bolster security and user trust;
    - Added default support to Metal rendering for macOS users as a first class citizen having OpenGL optional still. The performance and smoothness took a noticeable improvement due to the seamless integration on Apples specific hardware and it's a quite impactful merge;
    New Features
    - feat: add support of Metal renderer on macOS. by @crupest in https://github.com/neovide/neovide/pull/2461
    - on macOS, activate when launched by @fboundp in https://github.com/neovide/neovide/pull/2799
    - feat: add normal opacity by @lucobellic in https://github.com/neovide/neovide/pull/2780
    - feat: add mouse cursor icon option by @falcucci in https://github.com/neovide/neovide/pull/2834
    - disable AppKit's command line processing by @fboundp in https://github.com/neovide/neovide/pull/2798
    - Update syn to 2.x to reduce package repetition in the binary by @Kethku in https://github.com/neovide/neovide/pull/2811
    - Windows app icon to display in old alt+tab on Windows. by @madcdevelop in https://github.com/neovide/neovide/pull/2816
    - Remove lazy_static by @InfyniteHeap in https://github.com/neovide/neovide/pull/2821
    - internal: Use macOS-latest runners and bump MACOSX_DEPLOYMENT_TARGET to 10.11 by @falcucci in https://github.com/neovide/neovide/pull/2844
    - feat: Rounded floating windows (#1993) by @jheroy in https://github.com/neovide/neovide/pull/2743
    - feat: create apple code signing and notarization by @falcucci in https://github.com/neovide/neovide/pull/2814
    - feat: add title bar colours for windows by @teehee567 in https://github.com/neovide/neovide/pull/2827
    - Initialize the window when 'win_viewport_margins' is received by @fredizzimo in https://github.com/neovide/neovide/pull/2904
    - feat: backtraces file path config in https://github.com/neovide/neovide/pull/2717
    Bug Fixes
    - fix: Force Neovide to exit, even if the IO streams are not closed by @fredizzimo in https://github.com/neovide/neovide/pull/2765
    - fix: drag and drop files on application icon in Dock to open not work. by @crupest in https://github.com/neovide/neovide/pull/2782
    - fix: Mouse scrolling when multigrid is disabled by @fredizzimo in https://github.com/neovide/neovide/pull/2805
    - fix: Update winit to 0.30.5 by @fredizzimo in https://github.com/neovide/neovide/pull/2806
    - Fix macos download link by @Kethku in https://github.com/neovide/neovide/pull/2808
    - fix: error if trying to specify font style overrides without a family by @xzbdmw in https://github.com/neovide/neovide/pull/2812
    - bug: make sure to load and set the app icon for any context by @falcucci in https://github.com/neovide/neovide/pull/2832
    - fix: ci build errors by @fredizzimo in https://github.com/neovide/neovide/pull/2851
    - Fix: --wayland_app_id doesn't work by @floflo0 in https://github.com/neovide/neovide/pull/2847
    - fix: rounded corners rendering by @lucobellic in https://github.com/neovide/neovide/pull/2857
    - fix: pasting ^M symbols from clipboard by @damiandimanov in https://github.com/neovide/neovide/pull/2869
    - fix: handle font changes during frame prepare by @fredizzimo in https://github.com/neovide/neovide/pull/2909
    - fix: setting of lines/columns on Wayland by @fredizzimo in https://github.com/neovide/neovide/pull/2907
    - fix: the calculation of the window size by @fredizzimo in https://github.com/neovide/neovide/pull/2908
    - fix: the calculation of the window size (attempt 2) by @fredizzimo in https://github.com/neovide/neovide/pull/2912
    - fix: crash when flushed before win_pos by @fredizzimo in https://github.com/neovide/neovide/pull/2913
    - fix: Neovide transparency works for floating windows again by @fredizzimo in https://github.com/neovide/neovide/pull/2916
    - fix: add text_background_opacity in the opaque validation by @falcucci in https://github.com/neovide/neovide/pull/2917
    Other Changes
    - docs: improve installation instructions and build steps for macOS by @falcucci in https://github.com/neovide/neovide/pull/2875
    - Add faq entry for disabling all animations by @Kethku in https://github.com/neovide/neovide/pull/2810
    - docs: consolidate macOS build instructions and scripts by @falcucci in https://github.com/neovide/neovide/pull/2716
    - chore: Update dependencies by @fredizzimo in https://github.com/neovide/neovide/pull/2902
    - chore: fix the formatting by @fredizzimo in https://github.com/neovide/neovide/pull/2903
    - chore: Switch to glamour instead of euclid by @fredizzimo in https://github.com/neovide/neovide/pull/2708
    - chore: Update to winit 0.30.3 by @fredizzimo in https://github.com/neovide/neovide/pull/2698
    - chore: update create-dmg package installation by @falcucci in https://github.com/neovide/neovide/pull/2756
    - chore: update objc2 and remove icrate. also some refactor. by @crupest in https://github.com/neovide/neovide/pull/2768
    - chore: update funding to open_collective by @falcucci in https://github.com/neovide/neovide/pull/2880
    - chore: add stylua.toml and format code by @lucobellic in https://github.com/neovide/neovide/pull/2823
    - chore: update skia-safe version to 0.80.0 by @falcucci in https://github.com/neovide/neovide/pull/2873
    New Contributors
    - @fboundp made their first contribution in https://github.com/neovide/neovide/pull/2798
    - @madcdevelop made their first contribution in https://github.com/neovide/neovide/pull/2816
    - @jheroy made their first contribution in https://github.com/neovide/neovide/pull/2743
    - @floflo0 made their first contribution in https://github.com/neovide/neovide/pull/2847
    - @teehee567 made their first contribution in https://github.com/neovide/neovide/pull/2827
    - @damiandimanov made their first contribution in https://github.com/neovide/neovide/pull/2869
    Full Changelog: https://github.com/neovide/neovide/compare/0.13.3...0.14.0
    Funding
    Neovide will always be free and open-source, but it isn't free to make! Because Neovide is free, we rely on the generosity of the community to fund our efforts. If you are a happy user of Neovide, please consider donating. every bit helps!
    Project sponsorship and funding
    Neovide offers a simple sponsorship program that allows companies to get visibility and recognition among various developers.
    You can sponsor or fund the project via Open collective
- Key: ReleaseNotesUrl
  Value: https://github.com/neovide/neovide/releases/tag/0.14.0
Version: 0.14.0
ReleaseTime: 2025-01-03T10:05:43.0000000Z
