Installer:
- Architecture: x64
  InstallerUrl: https://github.com/neovide/neovide/releases/download/0.12.2/neovide.msi
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    What's Changed
    Breaking changes
    - neovide_background_color has been dreprecated, see https://github.com/neovide/neovide/pull/2168
    - On macOS, the title is not automatically hidden with --frame buttonless, enable it with --title-hidden (macOS specific)
    Features
    - feat: support all font weights and slants by @TwIStOy in https://github.com/neovide/neovide/pull/2246
    - feat: implement macOS window blur by @falcucci in https://github.com/neovide/neovide/pull/2273
    - feat: Add colored output to --help by @last-partizan in https://github.com/neovide/neovide/pull/2316
    - feat: implement dynamic window title visibility option by @falcucci in https://github.com/neovide/neovide/pull/2319
    Bug fixes
    - fix: #2233 by replacing echo command with api call by @genzj in https://github.com/neovide/neovide/pull/2241
      - Fixes hangs when errors or messages are shown at startup
    - fix: #2234 by adding !self.scrollback_lines.is_empty() check by @Mentalist in https://github.com/neovide/neovide/pull/2247
      - Freeze when opening neo-tree
    - fix: #2240 by swap item order in FontDescriptionSettings by @TwIStOy in https://github.com/neovide/neovide/pull/2244
      - Fallback fonts works in config.toml
    - fix: shadow artifacts on macOS by @falcucci in https://github.com/neovide/neovide/pull/2272
    - fix: When counting leading spaces for space skip optimization count codepoints by @ZyX-II in https://github.com/neovide/neovide/pull/2298
      - Special spaces like NBSP were rendered wrong
    - Fix issue with recursive floating window anchors by @Kethku in https://github.com/neovide/neovide/pull/2257
      - Crash when dragging the mouse
    - fix: Prevent the font from becoming zero sized by @fredizzimo in https://github.com/neovide/neovide/pull/2307
      - Crash when the font becomes too small
    - fix: Reset the cached font info after the fudge factor is updated by @fredizzimo in https://github.com/neovide/neovide/pull/2308
      - The letter spacing of the font could be wrong
    - fix: Error with guifont=* by @fredizzimo in https://github.com/neovide/neovide/pull/2309
    - Update dependencies and Winit to 0.29.10 by @fredizzimo in https://github.com/neovide/neovide/pull/2310
      - See https://github.com/rust-windowing/winit/releases for a full list of bugs fixed
    - fix: Use rpc request instead of notify for quit requests by @fredizzimo in https://github.com/neovide/neovide/pull/2312
    - Send options on startup as well as on changed except for columns and rows by @Kethku in https://github.com/neovide/neovide/pull/2315
      - Some options like mousemoveevent set from init.lua/vim were not applied
    - Fix shlex::join Deprecation Warning by @abhillman in https://github.com/neovide/neovide/pull/2314
    - feat!: fix appearance of --frame transparent and deprecate neovide_background_color. by @crupest in https://github.com/neovide/neovide/pull/2168
    - fix: fix hang on neovim exit by @sid-6581 in https://github.com/neovide/neovide/pull/2265
    New Contributors
    - @genzj made their first contribution in https://github.com/neovide/neovide/pull/2241
    - @Mentalist made their first contribution in https://github.com/neovide/neovide/pull/2247
    - @falcucci made their first contribution in https://github.com/neovide/neovide/pull/2272
    - @abhillman made their first contribution in https://github.com/neovide/neovide/pull/2314
    Full Changelog: https://github.com/neovide/neovide/compare/0.12.1...0.12.2
- Key: ReleaseNotesUrl
  Value: https://github.com/neovide/neovide/releases/tag/0.12.2
Version: 0.12.2
ReleaseTime: 2024-01-28T22:44:57.0000000Z
