Installer:
- Architecture: x64
  InstallerUrl: https://github.com/artempyanykh/marksman/releases/download/2024-12-18/marksman.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    What's Changed
    - misc: Make marksman-server.sh work from a symlink by @artempyanykh in https://github.com/artempyanykh/marksman/pull/378
    - misc: Change folder load log level to info by @artempyanykh in https://github.com/artempyanykh/marksman/pull/379
    - fix: Check for a bogus root folder in workspace/didChangeWorkspaceFolders request by @artempyanykh in https://github.com/artempyanykh/marksman/pull/380
    Full Changelog: https://github.com/artempyanykh/marksman/compare/2024-12-04...2024-12-18
- Key: ReleaseNotesUrl
  Value: https://github.com/artempyanykh/marksman/releases/tag/2024-12-18
Version: 2024.12.18
ReleaseTime: 2024-12-18T15:42:41.0000000Z
