Installer:
- Architecture: x64
  InstallerUrl: https://cdn.kde.org/ci-builds/system/dolphin/release-24.12/windows/dolphin-release_24.12-5226-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: DE9761F5C9DDAB8A3AEA8DCA5F407CB7CA6C8C5DAF07B1C8C2B05877A282FFC1
Locale: []
Version: 24.12-5226
RealVersion: 24.12.2
