Installer:
- Architecture: x64
  InstallerUrl: https://github.com/dosbox-staging/dosbox-staging/releases/download/v0.81.1/dosbox-staging-windows-v0.81.1-setup.exe
- Architecture: x64
  InstallerUrl: https://github.com/dosbox-staging/dosbox-staging/releases/download/v0.81.1/dosbox-staging-windows-v0.81.1-setup.exe
- Architecture: x64
  InstallerUrl: https://github.com/dosbox-staging/dosbox-staging/releases/download/v0.81.1/dosbox-staging-windows-v0.81.1.zip
  NestedInstallerFiles:
  - RelativeFilePath: dosbox-staging-v0.81.1\dosbox.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: '0. 81.1 release notes: https://dosbox-staging.github.io/releases/release-notes/0.81.1/'
- Key: ReleaseNotesUrl
  Value: https://github.com/dosbox-staging/dosbox-staging/releases/tag/v0.81.1
Version: 0.81.1
ReleaseTime: 2024-05-12T03:34:53.0000000Z
