Installer:
- Architecture: x64
  InstallerUrl: https://github.com/Hibbiki/chromium-win64/releases/download/v124.0.6367.61-r1274542/mini_installer.sync.exe
- Architecture: x64
  InstallerUrl: https://github.com/Hibbiki/chromium-win64/releases/download/v124.0.6367.61-r1274542/mini_installer.sync.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: a32f6839a38ef3d0283a11d5e4e084d8181171ce ../out/x64/mini_installer.sync.exe 341111d619ca24419f2252b2e11816968b244a88 ../out/x64/chrome.sync.7z e021e5ce239ced4eaa457c7889d0efb26d1ecefa ../out/x64/mini_installer.nosync.exe bf1334be0e27356cd4b30b18435bbf51bd5c96d0 ../out/x64/chrome.nosync.7z 76eaaacc07f89ff7194b24510ea146cfffe994b6 ../out/noarch/policy_templates.zip
- Key: ReleaseNotesUrl
  Value: https://github.com/Hibbiki/chromium-win64/releases/tag/v124.0.6367.61-r1274542
Version: 124.0.6367.61
ReleaseTime: 2024-04-17T09:46:05.0000000Z
