Installer:
- Architecture: x64
  InstallerUrl: https://github.com/WalletWasabi/WalletWasabi/releases/download/v2.0.7.2/Wasabi-2.0.7.2.msi
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Wasabi Wallet is an easy to use, privacy-focused, open-source, non-custodial, Bitcoin wallet
    Download
    :window: Windows :green_apple: Apple M1/M2 :apple: Apple Intel :penguin: Ubuntu / Debian :penguin: Other Linux

    Release Highlights
    🆕 Coinjoin to another wallet
    Release Summary
    What is this release about?
    This version is just adding one feature: Mix to another wallet - In the program, you can set another wallet in the coinjoin settings to which you want to coinjoin. In this case, the anonymity score target is not considered; once the coinjoin is completed, your coins will be transferred to the wallet you specified.

    Read the related blog for more information.
    Installation Guide
    Download the operating system relevant software package and install Wasabi like you would with any other software on your computer. For a detailed installation guide, including signature verification, see the documentation.
    Documentation
    :spider_web: Website :onion: Tor onion site :orange_book: Documentation :grey_question: FAQ
    Advanced Guide
    If you want to build or update Wasabi from source code, check out these easy instructions.
    Wasabi uses reproducible builds, which you can verify with this guide.
    Requirements
    - Windows 10 1607+
    - Windows 11 22000+
    - macOS 12.0+
    - Ubuntu 22.04+
    - Fedora 37+
    - Debian 11+

    Full Changelog
    What's Changed
    - [v2.0.7.2] Mix to another wallet clean by @Whem in https://github.com/zkSNACKs/WalletWasabi/pull/12997
    - Fix coin join real start by @Whem in https://github.com/zkSNACKs/WalletWasabi/pull/13013
    Full Changelog: https://github.com/zkSNACKs/WalletWasabi/compare/v2.0.7.1...v2.0.7.2
- Key: ReleaseNotesUrl
  Value: https://github.com/WalletWasabi/WalletWasabi/releases/tag/v2.0.7.2
Version: 2.0.7.2
ReleaseTime: 2024-05-13T10:54:47.0000000Z
