Installer:
- Architecture: x86
  InstallerUrl: https://github.com/UniversalMediaServer/UniversalMediaServer/releases/download/13.10.1/UMS-13.10.1.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Summary
    This release fixes a number of bugs on all renderers, particularly Samsung QLED and LG OLED TVs and Sony PlayStation 4.
    We have finally reached the end of the known v14 bugs so this is very likely to be the last v13 release. Thank you for your patience and support!
    This release is available via our Patreon page, and will be available here when the next release happens.
    Changes
    General
    - Fixed MP4 and WMV transcoding
    - Fixed MKV detection on some renderers
    - Fixed detection of Dolby Vision hvc1 variant
    - Fixed FFmpeg not remuxing E-AC3 when supported
    - Fixed videos being incorrectly marked as fully played
    Renderers
    - Improved support for MP4 files on Samsung QLED TVs
    - Improved detection of Samsung QLED TVs
    - Fixed playback of H.264 videos over level 4.2 on PS4
    Dependencies
    - Bump @testing-library/react from 14.2.1 to 15.0.2 (#4583)
    - Bump @types/lodash from 4.14.202 to 4.17.0 (#4569)
    - Bump @types/node from 18.19.28 to 18.19.31 (#4597)
    - Bump @types/react-dom from 18.2.23 to 18.2.25 (#4596)
    - Bump @types/react from 18.2.64 to 18.2.79 (#4582, #4598)
    - Bump @typescript-eslint/eslint-plugin from 7.4.0 to 7.7.1 (#4581, #4603)
    - Bump @typescript-eslint/parser from 7.4.0 to 7.7.1 (#4581, #4603)
    - Bump axios from 1.6.7 to 1.6.8 (#4568)
    - Bump commons-io:commons-io from 2.16.0 to 2.16.1 (#4585)
    - Bump JRE from 17.0.10 to 17.0.11
    - Bump logback-version from 1.5.3 to 1.5.6 (#4584, #4599)
    - Bump org.apache.commons:commons-text from 1.11.0 to 1.12.0 (#4600)
    - Bump org.slf4j:slf4j-api from 2.0.12 to 2.0.13 (#4586)
    - Bump tar from 6.2.0 to 6.2.1 (#4575)
    - Bump typescript from 5.4.3 to 5.4.5 (#4570, #4595)
- Key: ReleaseNotesUrl
  Value: https://github.com/UniversalMediaServer/UniversalMediaServer/releases/tag/13.10.1
Version: 13.10.1
ReleaseTime: 2024-05-01T04:26:53.0000000Z
