Installer:
- Architecture: x86
  InstallerUrl: https://github.com/UniversalMediaServer/UniversalMediaServer/releases/download/14.7.0/UMS-14.7.0.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Summary
    We have started releasing UMS in the AppImage format! This adds to the growing list of ways to install and update.
    This release also expands our UPnP support, fixes many different video playback bugs, improves LG and Samsung TV support, and more!
    Changes
    General
    - Started releasing AppImages (thanks, @Samueru-sama and @Twig6943!)
    - Extended UPnP CreateObject / ImportUri support
    - Removed Netty dependency
    - Updated TMDB API schemas to 24/09/2024
    - Fixed URI bug when using TMDB directly
    - Fixed not playing videos without audio tracks (#5014) (thanks, @Nothsor!)
    - Fixed not playing videos when transcoding on some players (#4919, #5015) (thanks, @mykeehu, @SpitFire-666, and wolfgangsaul!)
    - Logging improvements
    Media players
    - Samsung TVs: Fixed thumbnails not updating (thanks, @Fredo1650!)
    - LG TVs: Fixed not directly playing non-mod4 (resolution divisible by 4) videos
    - LG TVs: Fixed playback of DivX and XviD videos (thanks, Dušan Kazik!)
    Translation updates via Crowdin
    - Afrikaans (12%) (thanks, Dusty Pienaar!)
    - Czech (100%)
    - Finnish (67%) (thanks, Esko Gardner!)
    - French (100%) (thanks, Fredo1650!)
    - Hungarian (64%) (thanks, Blaszlo!)
    - Japanese (71%) (thanks, elepro!)
    - Korean (100%) (thanks, VenusGirl!)
    - Polish (56%) (thanks, Karol Szastok!)
    - Slovak (47%) (thanks Dušan!)
    - Turkish (100%) (thanks, Burak Yavuz!)
    Dependencies
    - Bump @mantine/core from 7.13.0 to 7.13.4 (#5016, #5041, #5063)
    - Bump @mantine/dropzone from 7.13.0 to 7.13.4 (#5016, #5041, #5063)
    - Bump @mantine/form from 7.13.0 to 7.13.4 (#5016, #5041, #5063)
    - Bump @mantine/hooks from 7.13.0 to 7.13.4 (#5016, #5041, #5063)
    - Bump @mantine/modals from 7.13.0 to 7.13.4 (#5016, #5041, #5063)
    - Bump @mantine/notifications from 7.13.0 to 7.13.4 (#5016, #5041, #5063)
    - Bump @playwright/test from 1.47.0 to 1.48.2 (#5033, #5043, #5070)
    - Bump @types/lodash from 4.17.7 to 4.17.12 (#5030, #5064)
    - Bump @types/react-dom from 18.3.0 to 18.3.1 (#5044)
    - Bump @types/react from 18.3.10 to 18.3.12 (#5032, #5064)
    - Bump @vitejs/plugin-react from 4.3.2 to 4.3.3 (#5049)
    - Bump ch.qos.logback:logback-classic from 1.5.8 to 1.5.12 (#5058)
    - Bump ch.qos.logback:logback-core from 1.5.8 to 1.5.12 (#5058)
    - Bump com.github.oshi:oshi-core from 6.6.4 to 6.6.5 (#5028)
    - Bump com.puppycrawl.tools:checkstyle from 10.18.2 to 10.19.0 (#5072)
    - Bump com.twelvemonkeys.imageio:imageio-batik from 3.11.0 to 3.12.0 (#5059)
    - Bump com.twelvemonkeys.imageio:imageio-bmp from 3.11.0 to 3.12.0 (#5059)
    - Bump com.twelvemonkeys.imageio:imageio-core from 3.11.0 to 3.12.0 (#5059)
    - Bump com.twelvemonkeys.imageio:imageio-hdr from 3.11.0 to 3.12.0 (#5059)
    - Bump com.twelvemonkeys.imageio:imageio-icns from 3.11.0 to 3.12.0 (#5059)
    - Bump com.twelvemonkeys.imageio:imageio-iff from 3.11.0 to 3.12.0 (#5059)
    - Bump com.twelvemonkeys.imageio:imageio-jpeg from 3.11.0 to 3.12.0 (#5059)
    - Bump com.twelvemonkeys.imageio:imageio-metadata from 3.11.0 to 3.12.0 (#5059)
    - Bump com.twelvemonkeys.imageio:imageio-pcx from 3.11.0 to 3.12.0 (#5059)
    - Bump com.twelvemonkeys.imageio:imageio-pict from 3.11.0 to 3.12.0 (#5059)
    - Bump com.twelvemonkeys.imageio:imageio-pnm from 3.11.0 to 3.12.0 (#5059)
    - Bump com.twelvemonkeys.imageio:imageio-psd from 3.11.0 to 3.12.0 (#5059)
    - Bump com.twelvemonkeys.imageio:imageio-sgi from 3.11.0 to 3.12.0 (#5059)
    - Bump com.twelvemonkeys.imageio:imageio-tga from 3.11.0 to 3.12.0 (#5059)
    - Bump com.twelvemonkeys.imageio:imageio-tiff from 3.11.0 to 3.12.0 (#5059)
    - Bump eslint-plugin-react-refresh from 0.4.12 to 0.4.13 (#5050)
    - Bump eslint-plugin-react from 7.36.1 to 7.37.2 (#5019, #5065)
    - Bump eslint from 9.11.0 to 9.13.0 (#5017, #5069)
    - Bump jetty.version from 12.0.13 to 12.0.14 (#5022)
    - Bump JRE to 17.0.13+12
    - Bump junit5.version from 5.11.1 to 5.11.2 (#5020)
    - Bump NSIS from 3.09 to 3.10
    - Bump org.apache.maven.plugins:maven-checkstyle-plugin from 3.5.0 to 3.6.0 (#5074)
    - Bump org.apache.maven.plugins:maven-surefire-plugin from 3.5.0 to 3.5.1 (#5021)
    - Bump org.apache.xmlgraphics:batik-svgrasterizer from 1.17 to 1.18 (#5029)
    - Bump org.codehaus.mojo:exec-maven-plugin from 3.4.1 to 3.5.0 (#5060)
    - Bump org.junit.jupiter:junit-jupiter-engine from 5.11.2 to 5.11.3 (#5080)
    - Bump react-router-dom from 6.26.1 to 6.27.0 (#5003, #5034)
    - Bump tsMuxeR to 2024-06-06-02-00-53
    - Bump typescript-eslint from 8.7.0 to 8.12.1 (#5079)
    - Bump typescript from 5.6.2 to 5.6.3 (#5047)
    - Bump video.js from 8.17.4 to 8.19.1 (#5042, #5068)
    - Bump vite from 5.4.7 to 5.4.9 (#5018, #5048)
- Key: ReleaseNotesUrl
  Value: https://github.com/UniversalMediaServer/UniversalMediaServer/releases/tag/14.7.0
Version: 14.7.0
ReleaseTime: 2024-11-02T00:32:44.0000000Z
