Installer:
- Architecture: x64
  InstallerUrl: https://cdn.kde.org/ci-builds/utilities/ark/release-24.12/windows/ark-release_24.12-2038-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: 893FCF3C096358C19A3636409CDBA43CC1BF6AE3DC96F6EB63CCB59ADE851768
Locale: []
Version: 24.12-2038
RealVersion: 24.12.1
