Installer:
- Architecture: x86
  InstallerUrl: https://github.com/Tyrrrz/LightBulb/releases/download/2.5.1/LightBulb-Installer.win-arm64.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    What's Changed
    - Trim produced assemblies by @Tyrrrz in https://github.com/Tyrrrz/LightBulb/pull/302
    Full Changelog: https://github.com/Tyrrrz/LightBulb/compare/2.5...2.5.1
- Key: ReleaseNotesUrl
  Value: https://github.com/Tyrrrz/LightBulb/releases/tag/2.5.1
Version: 2.5.1
ReleaseTime: 2024-05-26T20:14:27.0000000Z
