Installer:
- Architecture: x86
  InstallerUrl: https://github.com/HandBrake/HandBrake/releases/download/1.7.3/HandBrake-1.7.3-x86_64-Win_GUI.exe
- Architecture: x64
  InstallerUrl: https://github.com/HandBrake/HandBrake/releases/download/1.7.3/HandBrake-1.7.3-x86_64-Win_GUI.exe
- Architecture: arm64
  InstallerUrl: https://github.com/HandBrake/HandBrake/releases/download/1.7.3/HandBrake-1.7.3-arm64-Win_GUI.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Upgrade Notice
    Before updating HandBrake, please make sure there are no pending encodes in the queue, and be sure to make a backup of any custom presets and app preferences you have, as they may not be compatible with newer versions.
    Windows users, please make sure to install Microsoft .NET Desktop Runtime version 6.0.x. Read carefully: you need the DESKTOP runtime. You must install .NET 6 even if you have installed .NET 7 or 8
    HandBrake 1.7.3
    All platforms
    General
    - Fixed formatting leading zeros for timestamps in logs
    - Miscellaneous bug fixes and improvements
    Video
    - Fixed an issue that could potentially cause incorrect detection of source FPS value (#5677)
    Subtitles
    - Fixed tx3g to SSA subtitles conversion
    Linux
    - Fixed the "All Files" open file dialog filter to really show all files
    - Fixed an issue where adding a new default audio track automatically set the gain to -20 dB
    Mac
    - Fixed a regression introduced in HandBrake 1.7.2 by the workaround for VideoToolbox crashes on Sonoma
    - Miscellaneous bug fixes and improvements
    Windows
    - Improved security hardening of loading of DLL files within libhb by limiting search scope (#5724)
    - Improved keyboard navigation on Chapters tab (#5679)
    - Fixed an issue that could cause encodes to appear stalled when process isolation is turned on
    - Fixed an issue that could prevent QSV decode from being used when a system also has a non-Intel GPU
    - Fixed an issue where the drive label was not always correctly detected (#5711)
    - Miscellaneous bug fixes and improvements
- Key: ReleaseNotesUrl
  Value: https://github.com/HandBrake/HandBrake/releases/tag/1.7.3
Version: 1.7.3
ReleaseTime: 2024-02-11T11:05:27.0000000Z
